/**
 * Platform-plane synthetic dataset.
 *
 * WHY THIS EXISTS
 * ---------------
 * Five Platform views (Failed Jobs, Incidents, Integrations, System Health,
 * Release Dashboard) shipped with state initialised to `[]` and no loader —
 * `IncidentsView` never called `setIncidents` at all, and
 * `IntegrationsHealthView` did not even destructure a setter. They could not
 * render a row under any circumstance. This module gives the Platform console a
 * real dataset to exercise those surfaces before VowOS has a customer fleet.
 *
 * ISOLATION CONTRACT (see PLATFORM demo plane in platformDataSource.ts)
 * --------------------------------------------------------------------
 * This data is ONLY served when the Platform demo plane is explicitly active,
 * and every surface that renders it also renders a persistent banner. It must
 * never be summed into real MRR/ARR, churn, SLA, or health. A number a Platform
 * Owner cannot distinguish from production is worse than no number.
 */

const DAY = 24 * 60 * 60 * 1000;
const daysAgo = (n: number) => new Date(Date.now() - n * DAY).toISOString();
const hoursAgo = (n: number) => new Date(Date.now() - n * 60 * 60 * 1000).toISOString();
const inHours = (n: number) => new Date(Date.now() + n * 60 * 60 * 1000).toISOString();

export type LifecycleStage =
  | 'TRIAL' | 'IMPLEMENTATION' | 'READY_TO_GO_LIVE' | 'LIVE'
  | 'AT_RISK' | 'PAST_DUE' | 'SUSPENDED' | 'INTERNAL';

export interface DemoOrganization {
  id: string;
  name: string;
  slug: string;
  tenantDomain: string;
  lifecycle: LifecycleStage;
  operationalStatus: 'ACTIVE' | 'READ_ONLY' | 'SUSPENDED' | 'SECURITY_LOCK';
  onboardingStatus: 'NOT_STARTED' | 'IN_PROGRESS' | 'COMPLETE';
  onboardingPct: number;
  plan: string;
  billingInterval: 'MONTHLY' | 'ANNUAL';
  mrrCents: number;          // 0 for internal/comped — excluded from paying MRR
  comped: boolean;
  internal: boolean;
  businesses: { id: string; name: string; locations: { id: string; name: string; city: string }[] }[];
  userCount: number;
  openTickets: number;
  integrationHealth: 'HEALTHY' | 'DEGRADED' | 'FAILED' | 'NOT_CONNECTED';
  createdAt: string;
  lastActivityAt: string;
  csOwner: string;
}

export const DEMO_ORGANIZATIONS: DemoOrganization[] = [
  {
    id: 'org-roberts', name: 'Roberts Enterprises', slug: 'roberts-enterprises',
    tenantDomain: 'roberts-enterprises.vowos.bridgebox.ai',
    lifecycle: 'INTERNAL', operationalStatus: 'ACTIVE', onboardingStatus: 'COMPLETE', onboardingPct: 100,
    plan: 'Enterprise (Internal)', billingInterval: 'ANNUAL', mrrCents: 0, comped: true, internal: true,
    businesses: [
      { id: 'biz-ido', name: 'I Do Bridal Couture', locations: [
        { id: 'loc-ido-br', name: 'Baton Rouge', city: 'Baton Rouge, LA' },
        { id: 'loc-ido-cov', name: 'Covington', city: 'Covington, LA' },
      ]},
      { id: 'biz-proper', name: 'Proper & Co.', locations: [
        { id: 'loc-pc-br', name: 'Perkins Rowe', city: 'Baton Rouge, LA' },
      ]},
    ],
    userCount: 14, openTickets: 0, integrationHealth: 'HEALTHY',
    createdAt: daysAgo(420), lastActivityAt: hoursAgo(2), csOwner: 'Ned Pearson',
  },
  {
    id: 'org-magnolia', name: 'Magnolia Bridal Group', slug: 'magnolia-bridal',
    tenantDomain: 'magnolia-bridal.vowos.bridgebox.ai',
    lifecycle: 'LIVE', operationalStatus: 'ACTIVE', onboardingStatus: 'COMPLETE', onboardingPct: 100,
    plan: 'Growth', billingInterval: 'MONTHLY', mrrCents: 44900, comped: false, internal: false,
    businesses: [{ id: 'biz-mag', name: 'Magnolia Bridal', locations: [
      { id: 'loc-mag-dt', name: 'Downtown', city: 'Charleston, SC' },
      { id: 'loc-mag-mp', name: 'Mount Pleasant', city: 'Mt Pleasant, SC' },
    ]}],
    userCount: 11, openTickets: 1, integrationHealth: 'HEALTHY',
    createdAt: daysAgo(190), lastActivityAt: hoursAgo(1), csOwner: 'Ned Pearson',
  },
  {
    id: 'org-everly', name: 'Everly & Ash', slug: 'everly-ash',
    tenantDomain: 'everly-ash.vowos.bridgebox.ai',
    lifecycle: 'LIVE', operationalStatus: 'ACTIVE', onboardingStatus: 'COMPLETE', onboardingPct: 100,
    plan: 'Essentials', billingInterval: 'MONTHLY', mrrCents: 19900, comped: false, internal: false,
    businesses: [{ id: 'biz-everly', name: 'Everly & Ash Bridal', locations: [
      { id: 'loc-everly', name: 'Flagship', city: 'Nashville, TN' },
    ]}],
    userCount: 5, openTickets: 0, integrationHealth: 'HEALTHY',
    createdAt: daysAgo(150), lastActivityAt: hoursAgo(6), csOwner: 'Ned Pearson',
  },
  {
    id: 'org-lumiere', name: 'Lumière Formalwear', slug: 'lumiere-formalwear',
    tenantDomain: 'lumiere-formalwear.vowos.bridgebox.ai',
    lifecycle: 'AT_RISK', operationalStatus: 'ACTIVE', onboardingStatus: 'COMPLETE', onboardingPct: 100,
    plan: 'Growth', billingInterval: 'MONTHLY', mrrCents: 44900, comped: false, internal: false,
    businesses: [{ id: 'biz-lum', name: 'Lumière', locations: [
      { id: 'loc-lum-a', name: 'Uptown', city: 'Dallas, TX' },
      { id: 'loc-lum-b', name: 'Southlake', city: 'Southlake, TX' },
    ]}],
    userCount: 9, openTickets: 4, integrationHealth: 'FAILED',
    createdAt: daysAgo(240), lastActivityAt: daysAgo(9), csOwner: 'Ned Pearson',
  },
  {
    id: 'org-saintclair', name: 'Saint Clair Bridal', slug: 'saint-clair',
    tenantDomain: 'saint-clair.vowos.bridgebox.ai',
    lifecycle: 'PAST_DUE', operationalStatus: 'READ_ONLY', onboardingStatus: 'COMPLETE', onboardingPct: 100,
    plan: 'Essentials', billingInterval: 'MONTHLY', mrrCents: 19900, comped: false, internal: false,
    businesses: [{ id: 'biz-sc', name: 'Saint Clair', locations: [
      { id: 'loc-sc', name: 'Main Street', city: 'Savannah, GA' },
    ]}],
    userCount: 4, openTickets: 2, integrationHealth: 'DEGRADED',
    createdAt: daysAgo(300), lastActivityAt: daysAgo(3), csOwner: 'Ned Pearson',
  },
  {
    id: 'org-veil', name: 'The Veil Room', slug: 'veil-room',
    tenantDomain: 'veil-room.vowos.bridgebox.ai',
    lifecycle: 'IMPLEMENTATION', operationalStatus: 'ACTIVE', onboardingStatus: 'IN_PROGRESS', onboardingPct: 62,
    plan: 'Growth', billingInterval: 'ANNUAL', mrrCents: 40410, comped: false, internal: false,
    businesses: [{ id: 'biz-veil', name: 'The Veil Room', locations: [
      { id: 'loc-veil', name: 'Design District', city: 'Atlanta, GA' },
    ]}],
    userCount: 6, openTickets: 1, integrationHealth: 'NOT_CONNECTED',
    createdAt: daysAgo(24), lastActivityAt: hoursAgo(20), csOwner: 'Ned Pearson',
  },
  {
    id: 'org-ivory', name: 'Ivory Lane Bridal', slug: 'ivory-lane',
    tenantDomain: 'ivory-lane.vowos.bridgebox.ai',
    lifecycle: 'READY_TO_GO_LIVE', operationalStatus: 'ACTIVE', onboardingStatus: 'IN_PROGRESS', onboardingPct: 94,
    plan: 'Essentials', billingInterval: 'MONTHLY', mrrCents: 19900, comped: false, internal: false,
    businesses: [{ id: 'biz-ivory', name: 'Ivory Lane', locations: [
      { id: 'loc-ivory', name: 'Riverside', city: 'Greenville, SC' },
    ]}],
    userCount: 3, openTickets: 0, integrationHealth: 'HEALTHY',
    createdAt: daysAgo(18), lastActivityAt: hoursAgo(4), csOwner: 'Ned Pearson',
  },
  {
    id: 'org-blanc', name: 'Maison Blanc', slug: 'maison-blanc',
    tenantDomain: 'maison-blanc.vowos.bridgebox.ai',
    lifecycle: 'TRIAL', operationalStatus: 'ACTIVE', onboardingStatus: 'IN_PROGRESS', onboardingPct: 35,
    plan: 'Growth (Trial)', billingInterval: 'MONTHLY', mrrCents: 0, comped: false, internal: false,
    businesses: [{ id: 'biz-blanc', name: 'Maison Blanc', locations: [
      { id: 'loc-blanc', name: 'Magazine St', city: 'New Orleans, LA' },
    ]}],
    userCount: 2, openTickets: 0, integrationHealth: 'NOT_CONNECTED',
    createdAt: daysAgo(6), lastActivityAt: hoursAgo(11), csOwner: 'Ned Pearson',
  },
  {
    id: 'org-hemline', name: 'Hemline & Co.', slug: 'hemline-co',
    tenantDomain: 'hemline-co.vowos.bridgebox.ai',
    lifecycle: 'TRIAL', operationalStatus: 'ACTIVE', onboardingStatus: 'NOT_STARTED', onboardingPct: 8,
    plan: 'Essentials (Trial)', billingInterval: 'MONTHLY', mrrCents: 0, comped: false, internal: false,
    businesses: [{ id: 'biz-hem', name: 'Hemline', locations: [
      { id: 'loc-hem', name: 'Midtown', city: 'Memphis, TN' },
    ]}],
    userCount: 1, openTickets: 0, integrationHealth: 'NOT_CONNECTED',
    createdAt: daysAgo(3), lastActivityAt: daysAgo(2), csOwner: 'Ned Pearson',
  },
  {
    id: 'org-abbott', name: 'Abbott Formal', slug: 'abbott-formal',
    tenantDomain: 'abbott-formal.vowos.bridgebox.ai',
    lifecycle: 'SUSPENDED', operationalStatus: 'SUSPENDED', onboardingStatus: 'COMPLETE', onboardingPct: 100,
    plan: 'Essentials', billingInterval: 'MONTHLY', mrrCents: 0, comped: false, internal: false,
    businesses: [{ id: 'biz-abbott', name: 'Abbott Formal', locations: [
      { id: 'loc-abbott', name: 'Downtown', city: 'Mobile, AL' },
    ]}],
    userCount: 3, openTickets: 3, integrationHealth: 'FAILED',
    createdAt: daysAgo(390), lastActivityAt: daysAgo(41), csOwner: 'Ned Pearson',
  },
  {
    id: 'org-rowan', name: 'Rowan Bridal House', slug: 'rowan-bridal',
    tenantDomain: 'rowan-bridal.vowos.bridgebox.ai',
    lifecycle: 'LIVE', operationalStatus: 'ACTIVE', onboardingStatus: 'COMPLETE', onboardingPct: 100,
    plan: 'Growth', billingInterval: 'ANNUAL', mrrCents: 40410, comped: false, internal: false,
    businesses: [{ id: 'biz-rowan', name: 'Rowan Bridal', locations: [
      { id: 'loc-rowan-a', name: 'Highlands', city: 'Louisville, KY' },
      { id: 'loc-rowan-b', name: 'Lexington', city: 'Lexington, KY' },
      { id: 'loc-rowan-c', name: 'Cincinnati', city: 'Cincinnati, OH' },
    ]}],
    userCount: 17, openTickets: 1, integrationHealth: 'DEGRADED',
    createdAt: daysAgo(260), lastActivityAt: hoursAgo(3), csOwner: 'Ned Pearson',
  },
  {
    id: 'org-wren', name: 'Wren & Willow', slug: 'wren-willow',
    tenantDomain: 'wren-willow.vowos.bridgebox.ai',
    lifecycle: 'LIVE', operationalStatus: 'ACTIVE', onboardingStatus: 'COMPLETE', onboardingPct: 100,
    plan: 'Essentials', billingInterval: 'MONTHLY', mrrCents: 19900, comped: false, internal: false,
    businesses: [{ id: 'biz-wren', name: 'Wren & Willow', locations: [
      { id: 'loc-wren', name: 'Market Square', city: 'Knoxville, TN' },
    ]}],
    userCount: 6, openTickets: 0, integrationHealth: 'HEALTHY',
    createdAt: daysAgo(120), lastActivityAt: hoursAgo(9), csOwner: 'Ned Pearson',
  },
];

export const DEMO_FAILED_JOBS = [
  { id: 'job_8f21a', org: 'Lumière Formalwear', orgId: 'org-lumiere', type: 'shopify.orders.sync', status: 'FAILED', attempts: 5,
    lastError: 'HTTP 401 from Shopify Admin API — access token rejected (app uninstalled or scope revoked)',
    nextRetry: '—', impact: 'Online orders have not reached VowOS since ' + daysAgo(4).slice(0, 10), retrySafe: false, correlationId: 'cor_7d1e94' },
  { id: 'job_3b77c', org: 'Rowan Bridal House', orgId: 'org-rowan', type: 'growth.gbp.metrics', status: 'RETRYING', attempts: 2,
    lastError: 'Google Business Profile API quota exceeded (429)', nextRetry: inHours(2).slice(11, 16) + ' UTC',
    impact: 'Local SEO metrics stale for 2 locations', retrySafe: true, correlationId: 'cor_11ab03' },
  { id: 'job_c9e02', org: 'Saint Clair Bridal', orgId: 'org-saintclair', type: 'billing.invoice.charge', status: 'MANUAL_REVIEW', attempts: 3,
    lastError: 'Card declined — insufficient funds', nextRetry: '—',
    impact: 'Account moved to READ_ONLY after 3 failed attempts', retrySafe: false, correlationId: 'cor_55f7c1' },
  { id: 'job_1d440', org: 'Abbott Formal', orgId: 'org-abbott', type: 'messaging.sms.dispatch', status: 'FAILED', attempts: 4,
    lastError: 'Twilio 21610 — recipient has opted out of messages from this number', nextRetry: '—',
    impact: '1 appointment reminder not delivered', retrySafe: false, correlationId: 'cor_9c2280' },
  { id: 'job_6a815', org: 'The Veil Room', orgId: 'org-veil', type: 'import.bridallive.customers', status: 'RETRYING', attempts: 1,
    lastError: 'Row 1,284: required column "wedding_date" missing', nextRetry: inHours(1).slice(11, 16) + ' UTC',
    impact: 'Migration paused at 1,284 of 3,902 customers', retrySafe: true, correlationId: 'cor_402bb9' },
  { id: 'job_f0c73', org: 'Lumière Formalwear', orgId: 'org-lumiere', type: 'growth.attribution.rollup', status: 'FAILED', attempts: 6,
    lastError: 'Upstream dependency shopify.orders.sync has not succeeded — refusing to roll up partial revenue',
    nextRetry: '—', impact: 'ROAS reporting suppressed rather than shown wrong', retrySafe: true, correlationId: 'cor_7d1e94' },
];

export const DEMO_INCIDENTS = [
  { id: 'INC-2041', severity: 'SEV-2', status: 'MONITORING', title: 'Elevated Shopify webhook latency',
    affected: '3 organizations · 4 stores', started: hoursAgo(5),
    summary: 'Shopify webhook delivery p95 rose to 42s. Orders arrive but with delay. Mitigated by widening the worker pool.' },
  { id: 'INC-2040', severity: 'SEV-3', status: 'RESOLVED', title: 'Google Business Profile quota exhaustion',
    affected: '1 organization · 3 locations', started: daysAgo(2),
    summary: 'Daily GBP quota consumed by a retry storm on Rowan Bridal House. Backoff added.' },
  { id: 'INC-2039', severity: 'SEV-1', status: 'RESOLVED', title: 'Public booking pages returned 502',
    affected: 'All organizations', started: daysAgo(6),
    summary: 'A bad deploy removed the marketing route from server.js. Rolled back in 11 minutes. Post-deploy smoke now resolves redirects.' },
  { id: 'INC-2038', severity: 'SEV-2', status: 'INVESTIGATING', title: 'SMS opt-out list not syncing to reminders',
    affected: '2 organizations', started: hoursAgo(30),
    summary: 'Opt-out state is honoured at send time but not reflected in the UI, so staff re-queue messages that will never deliver.' },
];

import type {
  IntegrationTableRow,
  DiagnosticDrawerData,
  ProviderConnectionRecord,
  IntegrationCircuitBreaker,
  IntegrationErrorLog,
  IntegrationRecoveryTimeline,
  IntegrationSyncCursor,
  IntegrationDLQEvent,
  GoogleDriveWatch,
  FailureCategory,
  RecoveryActionType,
  IntegrationHealthStatus,
  CircuitState,
  AuthState,
} from '@/types/integrationOps';

export const DEMO_INTEGRATIONS: (IntegrationTableRow & {
  org: string;
  orgId: string;
  status: string;
  external: string;
  lastSync: string;
  errors24h: number;
  scopes: string;
})[] = [
  {
    id: 'conn-shopify-ido',
    business_id: 'biz-ido',
    brand_id: 'brand-ido',
    brand_name: 'I Do Bridal Couture',
    location_id: 'loc-ido-br',
    location_name: 'Baton Rouge Flagship',
    provider: 'Shopify',
    provider_account_id: 'ido-bridal-couture.myshopify.com',
    health_status: 'HEALTHY',
    circuit_breaker_state: 'CLOSED',
    auth_state: 'AUTHORIZED',
    last_event_at: hoursAgo(0.1),
    last_successful_sync_at: hoursAgo(0.1),
    recovery_status: 'Healthy (Real-time Webhooks Active)',
    sync_errors_24h: 0,
    is_auto_repairable: true,
    reconnect_url: null,
    metadata: { plan: 'Shopify Plus', webhooks_active: 6 },
    // Backwards-compatible aliases
    org: 'Roberts Enterprises',
    orgId: 'org-roberts',
    status: 'HEALTHY',
    external: 'ido-bridal-couture.myshopify.com',
    lastSync: hoursAgo(0.1),
    errors24h: 0,
    scopes: 'read_orders, write_inventory, read_customers',
  },
  {
    id: 'conn-ig-magnolia',
    business_id: 'biz-mag',
    brand_id: 'brand-mag',
    brand_name: 'Magnolia Bridal',
    location_id: 'loc-mag-dt',
    location_name: 'Downtown Charleston',
    provider: 'Instagram',
    provider_account_id: 'act_ig_magnoliabridal',
    health_status: 'RECOVERING',
    circuit_breaker_state: 'CLOSED',
    auth_state: 'AUTHORIZED',
    last_event_at: hoursAgo(0.3),
    last_successful_sync_at: hoursAgo(1.2),
    recovery_status: 'Auto-Repairing (Recreated Webhook & Syncing Missed DMs)',
    sync_errors_24h: 2,
    is_auto_repairable: true,
    reconnect_url: null,
    metadata: { page_id: '109823746198', webhook_recreated: true },
    org: 'Magnolia Bridal Group',
    orgId: 'org-magnolia',
    status: 'RECOVERING',
    external: '@magnoliabridal (act_ig_magnoliabridal)',
    lastSync: hoursAgo(1.2),
    errors24h: 2,
    scopes: 'instagram_basic, instagram_manage_messages',
  },
  {
    id: 'conn-fb-lumiere',
    business_id: 'biz-lum',
    brand_id: 'brand-lum',
    brand_name: 'Lumière Formalwear',
    location_id: 'loc-lum-a',
    location_name: 'Uptown Dallas',
    provider: 'Facebook',
    provider_account_id: 'act_fb_lumiere_formal',
    health_status: 'ACTION_REQUIRED',
    circuit_breaker_state: 'HALF_OPEN',
    auth_state: 'REVOKED',
    last_event_at: daysAgo(4),
    last_successful_sync_at: daysAgo(4),
    recovery_status: 'OAuth Token Revoked (1-Click Reconnect Required)',
    sync_errors_24h: 18,
    is_auto_repairable: false,
    reconnect_url: 'https://auth.vowos.com/oauth/facebook/reconnect?conn=conn-fb-lumiere',
    metadata: { revoked_reason: 'User changed Facebook password' },
    org: 'Lumière Formalwear',
    orgId: 'org-lumiere',
    status: 'ACTION REQUIRED',
    external: 'lumiere-formalwear-page',
    lastSync: daysAgo(4),
    errors24h: 18,
    scopes: 'pages_messaging, pages_read_engagement',
  },
  {
    id: 'conn-gbp-rowan',
    business_id: 'biz-rowan',
    brand_id: 'brand-rowan',
    brand_name: 'Rowan Bridal',
    location_id: 'loc-rowan-b',
    location_name: 'Lexington',
    provider: 'Google Business Profile',
    provider_account_id: 'accounts/109283749/locations/771',
    health_status: 'DEGRADED',
    circuit_breaker_state: 'OPEN',
    auth_state: 'AUTHORIZED',
    last_event_at: hoursAgo(1.5),
    last_successful_sync_at: hoursAgo(26),
    recovery_status: 'Rate Limited / 429 Quota (Circuit Open - Cooldown Active)',
    sync_errors_24h: 6,
    is_auto_repairable: true,
    reconnect_url: null,
    metadata: { quota_exceeded: true, retry_after_s: 45 },
    org: 'Rowan Bridal House',
    orgId: 'org-rowan',
    status: 'DEGRADED',
    external: 'Rowan Bridal Lexington (GBP)',
    lastSync: hoursAgo(26),
    errors24h: 6,
    scopes: 'business.manage, local.reviews',
  },
  {
    id: 'conn-stripe-proper',
    business_id: 'biz-proper',
    brand_id: 'brand-proper',
    brand_name: 'Proper & Co.',
    location_id: 'loc-pc-br',
    location_name: 'Perkins Rowe',
    provider: 'Stripe',
    provider_account_id: 'acct_1ProperCoBR99a',
    health_status: 'HEALTHY',
    circuit_breaker_state: 'CLOSED',
    auth_state: 'AUTHORIZED',
    last_event_at: hoursAgo(0.4),
    last_successful_sync_at: hoursAgo(0.4),
    recovery_status: 'Healthy (Charges & Webhooks Active)',
    sync_errors_24h: 0,
    is_auto_repairable: true,
    reconnect_url: null,
    metadata: { currency: 'usd', payouts_enabled: true },
    org: 'Roberts Enterprises',
    orgId: 'org-roberts',
    status: 'HEALTHY',
    external: 'acct_1ProperCoBR99a',
    lastSync: hoursAgo(0.4),
    errors24h: 0,
    scopes: 'charges, payouts, balance_history',
  },
  {
    id: 'conn-drive-everly',
    business_id: 'biz-everly',
    brand_id: 'brand-everly',
    brand_name: 'Everly & Ash Bridal',
    location_id: 'loc-everly',
    location_name: 'Flagship Nashville',
    provider: 'Google Drive',
    provider_account_id: 'gdrive_everly_contracts',
    health_status: 'HEALTHY',
    circuit_breaker_state: 'CLOSED',
    auth_state: 'AUTHORIZED',
    last_event_at: hoursAgo(0.1),
    last_successful_sync_at: hoursAgo(0.1),
    recovery_status: 'Healthy (Push Notification Watch Active)',
    sync_errors_24h: 0,
    is_auto_repairable: true,
    reconnect_url: null,
    metadata: { watch_channel: 'chn_drive_88192', watch_expires_in_hours: 160 },
    org: 'Everly & Ash',
    orgId: 'org-everly',
    status: 'HEALTHY',
    external: 'Everly & Ash Bridal Documents',
    lastSync: hoursAgo(0.1),
    errors24h: 0,
    scopes: 'drive.readonly, drive.file',
  },
  {
    id: 'conn-tiktok-saintclair',
    business_id: 'biz-sc',
    brand_id: 'brand-sc',
    brand_name: 'Saint Clair',
    location_id: 'loc-sc',
    location_name: 'Main Street Savannah',
    provider: 'TikTok',
    provider_account_id: 'tt_stclair_savannah',
    health_status: 'ACTION_REQUIRED',
    circuit_breaker_state: 'CLOSED',
    auth_state: 'EXPIRED',
    last_event_at: daysAgo(3),
    last_successful_sync_at: daysAgo(3),
    recovery_status: 'Token Expired (Re-authorization Required)',
    sync_errors_24h: 3,
    is_auto_repairable: false,
    reconnect_url: 'https://auth.vowos.com/oauth/tiktok/reconnect?conn=conn-tiktok-saintclair',
    metadata: { token_expired_at: daysAgo(3) },
    org: 'Saint Clair Bridal',
    orgId: 'org-saintclair',
    status: 'ACTION REQUIRED',
    external: '@saintclairbridal (TikTok)',
    lastSync: daysAgo(3),
    errors24h: 3,
    scopes: 'video.list, user.info.basic',
  },
  {
    id: 'conn-shopify-veil',
    business_id: 'biz-veil',
    brand_id: 'brand-veil',
    brand_name: 'The Veil Room',
    location_id: 'loc-veil',
    location_name: 'Design District Atlanta',
    provider: 'Shopify',
    provider_account_id: 'theveilroom-atl.myshopify.com',
    health_status: 'RECOVERING',
    circuit_breaker_state: 'CLOSED',
    auth_state: 'AUTHORIZED',
    last_event_at: hoursAgo(0.2),
    last_successful_sync_at: hoursAgo(1.5),
    recovery_status: 'Auto-Repairing (Replaying 3 DLQ Events)',
    sync_errors_24h: 1,
    is_auto_repairable: true,
    reconnect_url: null,
    metadata: { dlq_pending: 3, auto_healing_active: true },
    org: 'The Veil Room',
    orgId: 'org-veil',
    status: 'RECOVERING',
    external: 'theveilroom-atl.myshopify.com',
    lastSync: hoursAgo(1.5),
    errors24h: 1,
    scopes: 'read_orders, read_products',
  },
  {
    id: 'conn-twilio-abbott',
    business_id: 'biz-abbott',
    brand_id: 'brand-abbott',
    brand_name: 'Abbott Formal',
    location_id: 'loc-abbott',
    location_name: 'Downtown Mobile',
    provider: 'Twilio',
    provider_account_id: '+1 251 555 0192',
    health_status: 'ACTION_REQUIRED',
    circuit_breaker_state: 'CLOSED',
    auth_state: 'EXPIRED',
    last_event_at: daysAgo(41),
    last_successful_sync_at: daysAgo(41),
    recovery_status: 'Auth SID Invalid (Re-authorization Required)',
    sync_errors_24h: 4,
    is_auto_repairable: false,
    reconnect_url: 'https://auth.vowos.com/oauth/twilio/reconnect?conn=conn-twilio-abbott',
    metadata: { twilio_sid_revoked: true },
    org: 'Abbott Formal',
    orgId: 'org-abbott',
    status: 'ACTION REQUIRED',
    external: '+1 (251) 555-0192',
    lastSync: daysAgo(41),
    errors24h: 4,
    scopes: 'sms, messaging_service',
  },
];

/** Full synthetic diagnostic drawer data keyed by connection ID */
export const DEMO_INTEGRATION_DIAGNOSTICS: Record<string, DiagnosticDrawerData> = {
  'conn-shopify-ido': {
    connection: {
      id: 'conn-shopify-ido',
      business_id: 'biz-ido',
      brand_id: 'brand-ido',
      location_id: 'loc-ido-br',
      provider: 'shopify',
      provider_account_id: 'ido-bridal-couture.myshopify.com',
      status: 'active',
      capabilities: { webhooks: true, cursor_sync: true, live_orders: true },
      auth_token: 'shpat_9981273981274981729837198',
      health_status: 'HEALTHY',
      circuit_breaker_state: 'CLOSED',
      auth_state: 'AUTHORIZED',
      last_health_check_at: hoursAgo(0.1),
      last_successful_sync_at: hoursAgo(0.1),
      last_error_at: daysAgo(12),
      last_error_code: null,
      last_error_message: null,
      last_error_category: null,
      sync_errors_24h: 0,
      recovery_attempts: 0,
      last_recovery_at: daysAgo(12),
      reconnect_url: null,
      metadata: { webhook_count: 6, sync_mode: 'high-water-mark' },
      created_at: daysAgo(420),
      updated_at: hoursAgo(0.1),
    },
    circuitBreaker: {
      id: 'cb-shopify-ido',
      provider: 'shopify',
      scope: 'ACCOUNT',
      scope_id: 'conn-shopify-ido',
      business_id: 'biz-ido',
      state: 'CLOSED',
      failure_count: 0,
      consecutive_failures: 0,
      success_count: 14820,
      last_failure_at: daysAgo(12),
      last_success_at: hoursAgo(0.1),
      cooldown_expires_at: null,
      cooldown_seconds: 60,
      is_provider_outage: false,
      last_error_message: null,
      last_error_category: null,
      metadata: { threshold: 5 },
      created_at: daysAgo(420),
      updated_at: hoursAgo(0.1),
    },
    latestError: null,
    timeline: [
      {
        id: 'tl-ido-3',
        provider_connection_id: 'conn-shopify-ido',
        business_id: 'biz-ido',
        provider: 'shopify',
        action_type: 'RECONCILIATION_RUN',
        trigger: 'SCHEDULED_CRON',
        previous_status: 'HEALTHY',
        resulting_status: 'HEALTHY',
        details: { recordsIngested: 8, skippedDuplicates: 0, cursor: hoursAgo(0.1) },
        success: true,
        duration_ms: 185,
        executed_by: 'CRON_RUNNER',
        created_at: hoursAgo(0.1),
      },
      {
        id: 'tl-ido-2',
        provider_connection_id: 'conn-shopify-ido',
        business_id: 'biz-ido',
        provider: 'shopify',
        action_type: 'DIAGNOSTIC_RUN',
        trigger: 'AUTOMATIC',
        previous_status: 'HEALTHY',
        resulting_status: 'HEALTHY',
        details: { checksPassed: ['auth', 'webhooks', 'circuit', 'cursors'] },
        success: true,
        duration_ms: 64,
        executed_by: 'SYSTEM',
        created_at: hoursAgo(1),
      },
      {
        id: 'tl-ido-1',
        provider_connection_id: 'conn-shopify-ido',
        business_id: 'biz-ido',
        provider: 'shopify',
        action_type: 'WEBHOOK_RECREATED',
        trigger: 'AUTOMATIC',
        previous_status: 'RECOVERING',
        resulting_status: 'HEALTHY',
        details: { webhookId: 'wh_sh_ido_8820', topic: 'orders/create' },
        success: true,
        duration_ms: 220,
        executed_by: 'RECOVERY_ENGINE',
        created_at: daysAgo(12),
      },
    ],
    cursors: [
      {
        id: 'cur-ido-orders',
        provider_connection_id: 'conn-shopify-ido',
        business_id: 'biz-ido',
        resource_type: 'orders',
        last_cursor: hoursAgo(0.1),
        last_sync_timestamp: hoursAgo(0.1),
        buffer_seconds: 120,
        sync_status: 'IDLE',
        records_synced_total: 4892,
        records_synced_last_run: 8,
        lock_acquired_at: null,
        lock_expires_at: null,
        locked_by: null,
        last_error: null,
        metadata: { high_water_mark_id: 'ord_9948271' },
        created_at: daysAgo(420),
        updated_at: hoursAgo(0.1),
      },
      {
        id: 'cur-ido-products',
        provider_connection_id: 'conn-shopify-ido',
        business_id: 'biz-ido',
        resource_type: 'inventory',
        last_cursor: hoursAgo(2),
        last_sync_timestamp: hoursAgo(2),
        buffer_seconds: 120,
        sync_status: 'IDLE',
        records_synced_total: 1240,
        records_synced_last_run: 0,
        lock_acquired_at: null,
        lock_expires_at: null,
        locked_by: null,
        last_error: null,
        metadata: {},
        created_at: daysAgo(420),
        updated_at: hoursAgo(2),
      },
    ],
    dlqEvents: [],
    driveWatch: null,
  },

  'conn-ig-magnolia': {
    connection: {
      id: 'conn-ig-magnolia',
      business_id: 'biz-mag',
      brand_id: 'brand-mag',
      location_id: 'loc-mag-dt',
      provider: 'instagram',
      provider_account_id: 'act_ig_magnoliabridal',
      status: 'active',
      capabilities: { webhooks: true, direct_messages: true, comments: true },
      auth_token: 'EAAB...9824',
      health_status: 'RECOVERING',
      circuit_breaker_state: 'CLOSED',
      auth_state: 'AUTHORIZED',
      last_health_check_at: hoursAgo(0.3),
      last_successful_sync_at: hoursAgo(1.2),
      last_error_at: hoursAgo(1.2),
      last_error_code: '404',
      last_error_message: 'Webhook subscription was dropped by Meta Graph API drift',
      last_error_category: 'WEBHOOK_MISSING',
      sync_errors_24h: 2,
      recovery_attempts: 1,
      last_recovery_at: hoursAgo(0.3),
      reconnect_url: null,
      metadata: { instagram_business_account: '17841405309281' },
      created_at: daysAgo(190),
      updated_at: hoursAgo(0.3),
    },
    circuitBreaker: {
      id: 'cb-ig-mag',
      provider: 'instagram',
      scope: 'ACCOUNT',
      scope_id: 'conn-ig-magnolia',
      business_id: 'biz-mag',
      state: 'CLOSED',
      failure_count: 2,
      consecutive_failures: 0,
      success_count: 320,
      last_failure_at: hoursAgo(1.2),
      last_success_at: hoursAgo(0.3),
      cooldown_expires_at: null,
      cooldown_seconds: 60,
      is_provider_outage: false,
      last_error_message: 'Webhook missing 404',
      last_error_category: 'WEBHOOK_MISSING',
      metadata: {},
      created_at: daysAgo(190),
      updated_at: hoursAgo(0.3),
    },
    latestError: {
      id: 'err-ig-mag-1',
      provider_connection_id: 'conn-ig-magnolia',
      business_id: 'biz-mag',
      provider: 'instagram',
      endpoint: 'https://graph.facebook.com/v19.0/17841405309281/subscriptions',
      status_code: 404,
      failure_category: 'WEBHOOK_MISSING',
      error_message: 'Meta Graph API reported no active webhook for messaging topic on page 109823746198',
      root_cause: 'Webhook subscription expired during Meta Graph API v19 maintenance window. Incoming direct messages temporarily missed.',
      suggested_action: 'Automated remediation executed: Recreated webhook subscription via Graph API and initiated cursor-based backfill of missed DMs.',
      raw_payload: {
        error: {
          message: 'Object with ID 17841405309281 does not have an active webhook subscription for messages',
          type: 'OAuthException',
          code: 404,
          fbtrace_id: 'A9B8C7D6E5F4G3H2',
        },
      },
      sanitized_headers: {
        'x-fb-trace-id': 'A9B8C7D6E5F4G3H2',
        'x-app-usage': '{"call_count":12,"total_cputime":4,"total_time":6}',
        'content-type': 'application/json',
      },
      is_auto_repairable: true,
      is_resolved: true,
      resolved_at: hoursAgo(0.3),
      resolution_action: 'WEBHOOK_RECREATED',
      created_at: hoursAgo(1.2),
    },
    timeline: [
      {
        id: 'tl-mag-3',
        provider_connection_id: 'conn-ig-magnolia',
        business_id: 'biz-mag',
        provider: 'instagram',
        action_type: 'RECONCILIATION_RUN',
        trigger: 'AUTOMATIC',
        previous_status: 'RECOVERING',
        resulting_status: 'RECOVERING',
        details: { recordsIngested: 14, resource: 'direct_messages', backfillSpanMinutes: 72 },
        success: true,
        duration_ms: 380,
        executed_by: 'RECOVERY_ENGINE',
        created_at: hoursAgo(0.3),
      },
      {
        id: 'tl-mag-2',
        provider_connection_id: 'conn-ig-magnolia',
        business_id: 'biz-mag',
        provider: 'instagram',
        action_type: 'WEBHOOK_RECREATED',
        trigger: 'AUTOMATIC',
        previous_status: 'DEGRADED',
        resulting_status: 'RECOVERING',
        details: { subscription_id: 'sub_meta_998123', fields: ['messages', 'messaging_postbacks'] },
        success: true,
        duration_ms: 412,
        executed_by: 'RECOVERY_ENGINE',
        created_at: hoursAgo(0.3),
      },
      {
        id: 'tl-mag-1',
        provider_connection_id: 'conn-ig-magnolia',
        business_id: 'biz-mag',
        provider: 'instagram',
        action_type: 'DIAGNOSTIC_RUN',
        trigger: 'AUTOMATIC',
        previous_status: 'DEGRADED',
        resulting_status: 'RECOVERING',
        details: { rootCause: 'Webhook drift detected on Meta Graph API', category: 'WEBHOOK_MISSING' },
        success: true,
        duration_ms: 95,
        executed_by: 'SYSTEM',
        created_at: hoursAgo(0.3),
      },
    ],
    cursors: [
      {
        id: 'cur-ig-mag-dms',
        provider_connection_id: 'conn-ig-magnolia',
        business_id: 'biz-mag',
        resource_type: 'messages',
        last_cursor: hoursAgo(0.3),
        last_sync_timestamp: hoursAgo(0.3),
        buffer_seconds: 180,
        sync_status: 'RECOVERING',
        records_synced_total: 1542,
        records_synced_last_run: 14,
        lock_acquired_at: hoursAgo(0.01),
        lock_expires_at: inHours(0.1),
        locked_by: 'worker-instance-01',
        last_error: null,
        metadata: { backfill_in_progress: true },
        created_at: daysAgo(190),
        updated_at: hoursAgo(0.3),
      },
    ],
    dlqEvents: [],
    driveWatch: null,
  },

  'conn-fb-lumiere': {
    connection: {
      id: 'conn-fb-lumiere',
      business_id: 'biz-lum',
      brand_id: 'brand-lum',
      location_id: 'loc-lum-a',
      provider: 'facebook',
      provider_account_id: 'act_fb_lumiere_formal',
      status: 'error',
      capabilities: { lead_ads: true, page_inbox: true },
      auth_token: 'EAAG...revoked',
      health_status: 'ACTION_REQUIRED',
      circuit_breaker_state: 'HALF_OPEN',
      auth_state: 'REVOKED',
      last_health_check_at: hoursAgo(0.5),
      last_successful_sync_at: daysAgo(4),
      last_error_at: daysAgo(4),
      last_error_code: '190',
      last_error_message: 'Error validating access token: Session has been invalidated because the user changed their password or Facebook revoked the authorization.',
      last_error_category: 'AUTH_REVOKED',
      sync_errors_24h: 18,
      recovery_attempts: 3,
      last_recovery_at: hoursAgo(2),
      reconnect_url: 'https://auth.vowos.com/oauth/facebook/reconnect?conn=conn-fb-lumiere',
      metadata: { error_subcode: 460 },
      created_at: daysAgo(240),
      updated_at: hoursAgo(0.5),
    },
    circuitBreaker: {
      id: 'cb-fb-lum',
      provider: 'facebook',
      scope: 'ACCOUNT',
      scope_id: 'conn-fb-lumiere',
      business_id: 'biz-lum',
      state: 'HALF_OPEN',
      failure_count: 18,
      consecutive_failures: 5,
      success_count: 0,
      last_failure_at: hoursAgo(2),
      last_success_at: daysAgo(4),
      cooldown_expires_at: hoursAgo(1.5),
      cooldown_seconds: 300,
      is_provider_outage: false,
      last_error_message: 'OAuth token revoked (code 190)',
      last_error_category: 'AUTH_REVOKED',
      metadata: { max_retries_exceeded: true },
      created_at: daysAgo(240),
      updated_at: hoursAgo(2),
    },
    latestError: {
      id: 'err-fb-lum-1',
      provider_connection_id: 'conn-fb-lumiere',
      business_id: 'biz-lum',
      provider: 'facebook',
      endpoint: 'https://graph.facebook.com/v19.0/me/subscribed_apps',
      status_code: 401,
      failure_category: 'AUTH_REVOKED',
      error_message: 'HTTP 401: Invalid OAuth 2.0 access token (subcode 460). Password changed or token explicitly revoked by account manager.',
      root_cause: 'Lumière Formalwear page administrator updated their Meta Business Manager credentials, invalidating the long-lived page token.',
      suggested_action: 'OAuth re-authorization required. Send 1-click reconnect link to tenant owner (Ned Pearson / Lumière Admin).',
      raw_payload: {
        error: {
          message: 'Error validating access token: Session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.',
          type: 'OAuthException',
          code: 190,
          error_subcode: 460,
          fbtrace_id: 'Ez9X8W7V6U5T4S3R2',
        },
      },
      sanitized_headers: {
        'www-authenticate': 'OAuth "Facebook Platform" "invalid_token"',
        'x-fb-trace-id': 'Ez9X8W7V6U5T4S3R2',
      },
      is_auto_repairable: false,
      is_resolved: false,
      resolved_at: null,
      resolution_action: null,
      created_at: daysAgo(4),
    },
    timeline: [
      {
        id: 'tl-lum-3',
        provider_connection_id: 'conn-fb-lumiere',
        business_id: 'biz-lum',
        provider: 'facebook',
        action_type: 'RECONNECT_URL_GENERATED',
        trigger: 'AUTOMATIC',
        previous_status: 'DEGRADED',
        resulting_status: 'ACTION_REQUIRED',
        details: { reconnect_url: 'https://auth.vowos.com/oauth/facebook/reconnect?conn=conn-fb-lumiere', recipient: 'tenant_admin' },
        success: true,
        duration_ms: 45,
        executed_by: 'RECOVERY_ENGINE',
        created_at: hoursAgo(2),
      },
      {
        id: 'tl-lum-2',
        provider_connection_id: 'conn-fb-lumiere',
        business_id: 'biz-lum',
        provider: 'facebook',
        action_type: 'CIRCUIT_TRIPPED',
        trigger: 'AUTOMATIC',
        previous_status: 'DEGRADED',
        resulting_status: 'ACTION_REQUIRED',
        details: { consecutive_failures: 5, state: 'HALF_OPEN', reason: 'Unrecoverable 401 Auth Revocation' },
        success: true,
        duration_ms: 12,
        executed_by: 'CIRCUIT_BREAKER',
        created_at: daysAgo(4),
      },
      {
        id: 'tl-lum-1',
        provider_connection_id: 'conn-fb-lumiere',
        business_id: 'biz-lum',
        provider: 'facebook',
        action_type: 'DIAGNOSTIC_RUN',
        trigger: 'AUTOMATIC',
        previous_status: 'HEALTHY',
        resulting_status: 'DEGRADED',
        details: { classification: 'AUTH_REVOKED', isAutoRepairable: false },
        success: true,
        duration_ms: 88,
        executed_by: 'SYSTEM',
        created_at: daysAgo(4),
      },
    ],
    cursors: [
      {
        id: 'cur-fb-lum',
        provider_connection_id: 'conn-fb-lumiere',
        business_id: 'biz-lum',
        resource_type: 'lead_ads',
        last_cursor: daysAgo(4),
        last_sync_timestamp: daysAgo(4),
        buffer_seconds: 120,
        sync_status: 'FAILED',
        records_synced_total: 812,
        records_synced_last_run: 0,
        lock_acquired_at: null,
        lock_expires_at: null,
        locked_by: null,
        last_error: 'OAuth token revoked',
        metadata: {},
        created_at: daysAgo(240),
        updated_at: daysAgo(4),
      },
    ],
    dlqEvents: [
      {
        id: 'dlq-fb-lum-1',
        provider_connection_id: 'conn-fb-lumiere',
        business_id: 'biz-lum',
        provider: 'facebook',
        event_type: 'leadgen/new_lead',
        idempotency_key: 'lead_fb_882910398',
        payload: { leadgen_id: '882910398', form_id: '394827104928', page_id: '109283746' },
        headers: { 'x-hub-signature-256': 'sha256=9f8e7d...' },
        error_message: 'HTTP 401 Auth Revoked - Unable to fetch lead field data',
        retry_count: 5,
        max_retries: 5,
        next_retry_at: null,
        status: 'PENDING',
        replay_result: {},
        replayed_at: null,
        created_at: daysAgo(3),
        updated_at: daysAgo(3),
      },
    ],
    driveWatch: null,
  },

  'conn-gbp-rowan': {
    connection: {
      id: 'conn-gbp-rowan',
      business_id: 'biz-rowan',
      brand_id: 'brand-rowan',
      location_id: 'loc-rowan-b',
      provider: 'google_business_profile',
      provider_account_id: 'accounts/109283749/locations/771',
      status: 'active',
      capabilities: { local_seo: true, reviews: true, posts: true },
      auth_token: 'ya29.a0...8291',
      health_status: 'DEGRADED',
      circuit_breaker_state: 'OPEN',
      auth_state: 'AUTHORIZED',
      last_health_check_at: hoursAgo(1.5),
      last_successful_sync_at: hoursAgo(26),
      last_error_at: hoursAgo(1.5),
      last_error_code: '429',
      last_error_message: 'Quota exceeded for quota metric "Read requests" and limit "Read requests per minute per user" of service "mybusinessbusinessinformation.googleapis.com"',
      last_error_category: 'RATE_LIMITED',
      sync_errors_24h: 6,
      recovery_attempts: 2,
      last_recovery_at: hoursAgo(1.5),
      reconnect_url: null,
      metadata: { quota_bucket: 'read_requests_per_minute' },
      created_at: daysAgo(260),
      updated_at: hoursAgo(1.5),
    },
    circuitBreaker: {
      id: 'cb-gbp-rowan',
      provider: 'google_business_profile',
      scope: 'ACCOUNT',
      scope_id: 'conn-gbp-rowan',
      business_id: 'biz-rowan',
      state: 'OPEN',
      failure_count: 6,
      consecutive_failures: 3,
      success_count: 420,
      last_failure_at: hoursAgo(1.5),
      last_success_at: hoursAgo(26),
      cooldown_expires_at: inHours(0.01),
      cooldown_seconds: 60,
      is_provider_outage: false,
      last_error_message: 'Google Business Profile 429 Quota Exceeded',
      last_error_category: 'RATE_LIMITED',
      metadata: { retry_after: 45 },
      created_at: daysAgo(260),
      updated_at: hoursAgo(1.5),
    },
    latestError: {
      id: 'err-gbp-rowan-1',
      provider_connection_id: 'conn-gbp-rowan',
      business_id: 'biz-rowan',
      provider: 'google_business_profile',
      endpoint: 'https://mybusinessbusinessinformation.googleapis.com/v1/accounts/109283749/locations/771',
      status_code: 429,
      failure_category: 'RATE_LIMITED',
      error_message: 'Google API returned 429 Too Many Requests. Read quota exceeded for local business insights.',
      root_cause: 'Retry storm occurred across Rowan Bridal multi-location sync jobs. Rate limiting triggered by Google API gateways.',
      suggested_action: 'Circuit breaker tripped to OPEN to prevent further quota exhaustion. Cooldown expires in ~45 seconds, after which exponential backoff sync resumes.',
      raw_payload: {
        error: {
          code: 429,
          message: 'Resource has been exhausted (e.g. check quota).',
          status: 'RESOURCE_EXHAUSTED',
          details: [{ '@type': 'type.googleapis.com/google.rpc.QuotaFailure', violations: [{ subject: 'project:vowos-prod', description: 'Quota exceeded for read requests' }] }],
        },
      },
      sanitized_headers: {
        'retry-after': '45',
        'content-type': 'application/json; charset=UTF-8',
      },
      is_auto_repairable: true,
      is_resolved: false,
      resolved_at: null,
      resolution_action: null,
      created_at: hoursAgo(1.5),
    },
    timeline: [
      {
        id: 'tl-gbp-2',
        provider_connection_id: 'conn-gbp-rowan',
        business_id: 'biz-rowan',
        provider: 'google_business_profile',
        action_type: 'CIRCUIT_TRIPPED',
        trigger: 'AUTOMATIC',
        previous_status: 'HEALTHY',
        resulting_status: 'DEGRADED',
        details: { consecutive_failures: 3, state: 'OPEN', cooldown_seconds: 60, reason: '429 Rate Limit' },
        success: true,
        duration_ms: 10,
        executed_by: 'CIRCUIT_BREAKER',
        created_at: hoursAgo(1.5),
      },
      {
        id: 'tl-gbp-1',
        provider_connection_id: 'conn-gbp-rowan',
        business_id: 'biz-rowan',
        provider: 'google_business_profile',
        action_type: 'DIAGNOSTIC_RUN',
        trigger: 'AUTOMATIC',
        previous_status: 'HEALTHY',
        resulting_status: 'DEGRADED',
        details: { category: 'RATE_LIMITED', retryAfterSeconds: 45 },
        success: true,
        duration_ms: 70,
        executed_by: 'SYSTEM',
        created_at: hoursAgo(1.5),
      },
    ],
    cursors: [
      {
        id: 'cur-gbp-rowan',
        provider_connection_id: 'conn-gbp-rowan',
        business_id: 'biz-rowan',
        resource_type: 'reviews',
        last_cursor: hoursAgo(26),
        last_sync_timestamp: hoursAgo(26),
        buffer_seconds: 300,
        sync_status: 'FAILED',
        records_synced_total: 394,
        records_synced_last_run: 0,
        lock_acquired_at: null,
        lock_expires_at: null,
        locked_by: null,
        last_error: '429 Quota Exceeded',
        metadata: {},
        created_at: daysAgo(260),
        updated_at: hoursAgo(1.5),
      },
    ],
    dlqEvents: [],
    driveWatch: null,
  },

  'conn-drive-everly': {
    connection: {
      id: 'conn-drive-everly',
      business_id: 'biz-everly',
      brand_id: 'brand-everly',
      location_id: 'loc-everly',
      provider: 'google_drive',
      provider_account_id: 'gdrive_everly_contracts',
      status: 'active',
      capabilities: { file_watch: true, contract_ingestion: true },
      auth_token: 'ya29.c.b0...9912',
      health_status: 'HEALTHY',
      circuit_breaker_state: 'CLOSED',
      auth_state: 'AUTHORIZED',
      last_health_check_at: hoursAgo(0.1),
      last_successful_sync_at: hoursAgo(0.1),
      last_error_at: null,
      last_error_code: null,
      last_error_message: null,
      last_error_category: null,
      sync_errors_24h: 0,
      recovery_attempts: 0,
      last_recovery_at: hoursAgo(12),
      reconnect_url: null,
      metadata: { watch_channel_id: 'chn_drive_88192' },
      created_at: daysAgo(150),
      updated_at: hoursAgo(0.1),
    },
    circuitBreaker: {
      id: 'cb-drive-everly',
      provider: 'google_drive',
      scope: 'ACCOUNT',
      scope_id: 'conn-drive-everly',
      business_id: 'biz-everly',
      state: 'CLOSED',
      failure_count: 0,
      consecutive_failures: 0,
      success_count: 820,
      last_failure_at: null,
      last_success_at: hoursAgo(0.1),
      cooldown_expires_at: null,
      cooldown_seconds: 60,
      is_provider_outage: false,
      last_error_message: null,
      last_error_category: null,
      metadata: {},
      created_at: daysAgo(150),
      updated_at: hoursAgo(0.1),
    },
    latestError: null,
    timeline: [
      {
        id: 'tl-drive-2',
        provider_connection_id: 'conn-drive-everly',
        business_id: 'biz-everly',
        provider: 'google_drive',
        action_type: 'WATCH_RENEWED',
        trigger: 'SCHEDULED_CRON',
        previous_status: 'HEALTHY',
        resulting_status: 'HEALTHY',
        details: { channelId: 'chn_drive_88192', newExpiration: inHours(168), resourceUri: 'https://www.googleapis.com/drive/v3/files/contracts_root' },
        success: true,
        duration_ms: 290,
        executed_by: 'CRON_WATCH_RENEWER',
        created_at: hoursAgo(12),
      },
      {
        id: 'tl-drive-1',
        provider_connection_id: 'conn-drive-everly',
        business_id: 'biz-everly',
        provider: 'google_drive',
        action_type: 'TOKEN_REFRESHED',
        trigger: 'AUTOMATIC',
        previous_status: 'HEALTHY',
        resulting_status: 'HEALTHY',
        details: { tokenExpiry: inHours(1) },
        success: true,
        duration_ms: 140,
        executed_by: 'TOKEN_MANAGER',
        created_at: hoursAgo(1),
      },
    ],
    cursors: [
      {
        id: 'cur-drive-everly',
        provider_connection_id: 'conn-drive-everly',
        business_id: 'biz-everly',
        resource_type: 'documents',
        last_cursor: 'change_token_8892104',
        last_sync_timestamp: hoursAgo(0.1),
        buffer_seconds: 60,
        sync_status: 'IDLE',
        records_synced_total: 614,
        records_synced_last_run: 2,
        lock_acquired_at: null,
        lock_expires_at: null,
        locked_by: null,
        last_error: null,
        metadata: {},
        created_at: daysAgo(150),
        updated_at: hoursAgo(0.1),
      },
    ],
    dlqEvents: [],
    driveWatch: {
      id: 'watch-drive-everly',
      provider_connection_id: 'conn-drive-everly',
      business_id: 'biz-everly',
      channel_id: 'chn_drive_88192',
      resource_id: 'res_drive_root_folder_99',
      resource_uri: 'https://www.googleapis.com/drive/v3/files/contracts_root/watch',
      expiration_timestamp: inHours(168),
      token: 'client_token_everly_88192',
      status: 'ACTIVE',
      last_renewed_at: hoursAgo(12),
      renewal_error: null,
      metadata: { auto_renew_buffer_hours: 24 },
      created_at: daysAgo(150),
      updated_at: hoursAgo(12),
    },
  },
};

/**
 * Creates fallback diagnostic drawer data for any connection row.
 */
export function createFallbackDiagnostics(row: IntegrationTableRow): DiagnosticDrawerData {
  const isActionRequired = row.health_status === 'ACTION_REQUIRED';
  const isDegraded = row.health_status === 'DEGRADED';
  const isRecovering = row.health_status === 'RECOVERING';
  const isHealthy = row.health_status === 'HEALTHY';

  return {
    connection: {
      id: row.id,
      business_id: row.business_id,
      brand_id: row.brand_id,
      location_id: row.location_id,
      provider: row.provider.toLowerCase().replace(/\s+/g, '_'),
      provider_account_id: row.provider_account_id,
      status: isActionRequired ? 'error' : 'active',
      capabilities: { webhooks: true, cursor_sync: true },
      auth_token: isActionRequired ? null : 'shpat_demo_secret_token_991823',
      health_status: row.health_status,
      circuit_breaker_state: row.circuit_breaker_state,
      auth_state: row.auth_state,
      last_health_check_at: row.last_event_at || hoursAgo(1),
      last_successful_sync_at: row.last_successful_sync_at || hoursAgo(1),
      last_error_at: isHealthy ? null : hoursAgo(2),
      last_error_code: isActionRequired ? '401' : isDegraded ? '429' : null,
      last_error_message: isHealthy ? null : row.recovery_status,
      last_error_category: isActionRequired ? 'AUTH_REVOKED' : isDegraded ? 'RATE_LIMITED' : isRecovering ? 'WEBHOOK_MISSING' : null,
      sync_errors_24h: row.sync_errors_24h,
      recovery_attempts: isHealthy ? 0 : 1,
      last_recovery_at: isRecovering ? hoursAgo(0.5) : null,
      reconnect_url: row.reconnect_url,
      metadata: row.metadata || {},
      created_at: daysAgo(30),
      updated_at: hoursAgo(0.1),
    },
    circuitBreaker: {
      id: `cb-${row.id}`,
      provider: row.provider.toLowerCase().replace(/\s+/g, '_'),
      scope: 'ACCOUNT',
      scope_id: row.id,
      business_id: row.business_id,
      state: row.circuit_breaker_state,
      failure_count: row.sync_errors_24h,
      consecutive_failures: isDegraded ? 3 : isActionRequired ? 5 : 0,
      success_count: isHealthy ? 540 : 12,
      last_failure_at: isHealthy ? null : hoursAgo(2),
      last_success_at: hoursAgo(1),
      cooldown_expires_at: row.circuit_breaker_state === 'OPEN' ? inHours(0.02) : null,
      cooldown_seconds: 60,
      is_provider_outage: false,
      last_error_message: isHealthy ? null : row.recovery_status,
      last_error_category: isActionRequired ? 'AUTH_REVOKED' : isDegraded ? 'RATE_LIMITED' : null,
      metadata: {},
      created_at: daysAgo(30),
      updated_at: hoursAgo(0.1),
    },
    latestError: isHealthy
      ? null
      : {
          id: `err-${row.id}-1`,
          provider_connection_id: row.id,
          business_id: row.business_id,
          provider: row.provider,
          endpoint: `https://api.${row.provider.toLowerCase().replace(/\s+/g, '')}.com/v1/sync`,
          status_code: isActionRequired ? 401 : isDegraded ? 429 : 500,
          failure_category: (isActionRequired ? 'AUTH_REVOKED' : isDegraded ? 'RATE_LIMITED' : 'WEBHOOK_MISSING') as FailureCategory,
          error_message: row.recovery_status,
          root_cause: isActionRequired
            ? 'The third-party provider invalidated or revoked the access token credentials.'
            : isDegraded
            ? 'The provider endpoint returned rate-limit / quota exhaustion responses (429).'
            : 'Webhook event delivery failed or webhook registration dropped.',
          suggested_action: isActionRequired
            ? 'Operator or tenant must complete 1-click OAuth reconnection.'
            : 'Automated recovery engine will retry with exponential backoff.',
          raw_payload: {
            error: {
              code: isActionRequired ? 401 : 429,
              message: row.recovery_status,
              provider: row.provider,
            },
          },
          sanitized_headers: {
            'x-request-id': `req_${row.id.slice(0, 8)}`,
            'content-type': 'application/json',
          },
          is_auto_repairable: row.is_auto_repairable,
          is_resolved: isHealthy,
          resolved_at: isHealthy ? hoursAgo(1) : null,
          resolution_action: isHealthy ? 'AUTO_REPAIRED' : null,
          created_at: hoursAgo(2),
        },
    timeline: [
      {
        id: `tl-${row.id}-2`,
        provider_connection_id: row.id,
        business_id: row.business_id,
        provider: row.provider,
        action_type: (isActionRequired ? 'RECONNECT_URL_GENERATED' : isRecovering ? 'WEBHOOK_RECREATED' : 'RECONCILIATION_RUN') as RecoveryActionType,
        trigger: 'AUTOMATIC',
        previous_status: isHealthy ? 'RECOVERING' : 'DEGRADED',
        resulting_status: row.health_status,
        details: { recoveryStatus: row.recovery_status },
        success: true,
        duration_ms: 160,
        executed_by: 'RECOVERY_ENGINE',
        created_at: hoursAgo(0.5),
      },
      {
        id: `tl-${row.id}-1`,
        provider_connection_id: row.id,
        business_id: row.business_id,
        provider: row.provider,
        action_type: 'DIAGNOSTIC_RUN',
        trigger: 'AUTOMATIC',
        previous_status: 'HEALTHY',
        resulting_status: row.health_status,
        details: { health_status: row.health_status },
        success: true,
        duration_ms: 55,
        executed_by: 'SYSTEM',
        created_at: hoursAgo(2),
      },
    ],
    cursors: [
      {
        id: `cur-${row.id}-1`,
        provider_connection_id: row.id,
        business_id: row.business_id,
        resource_type: 'events',
        last_cursor: row.last_successful_sync_at || hoursAgo(1),
        last_sync_timestamp: row.last_successful_sync_at || hoursAgo(1),
        buffer_seconds: 120,
        sync_status: isRecovering ? 'RECOVERING' : isActionRequired ? 'FAILED' : 'IDLE',
        records_synced_total: 1040,
        records_synced_last_run: isRecovering ? 12 : 0,
        lock_acquired_at: null,
        lock_expires_at: null,
        locked_by: null,
        last_error: isHealthy ? null : row.recovery_status,
        metadata: {},
        created_at: daysAgo(30),
        updated_at: hoursAgo(0.5),
      },
    ],
    dlqEvents: [],
    driveWatch: null,
  };
}

export const DEMO_SYSTEM_HEALTH = [
  { name: 'Web (marketing + app)', status: 'OPERATIONAL', latencyMs: 118, failureRate: 0.0, lastCheck: hoursAgo(0.02), affectedOrgs: 0 },
  { name: 'Worker / API', status: 'OPERATIONAL', latencyMs: 74, failureRate: 0.001, lastCheck: hoursAgo(0.02), affectedOrgs: 0 },
  { name: 'Database (Postgres)', status: 'OPERATIONAL', latencyMs: 11, failureRate: 0.0, lastCheck: hoursAgo(0.03), affectedOrgs: 0 },
  { name: 'Supabase Auth', status: 'OPERATIONAL', latencyMs: 96, failureRate: 0.0, lastCheck: hoursAgo(0.03), affectedOrgs: 0 },
  { name: 'Background jobs', status: 'DEGRADED', latencyMs: 2400, failureRate: 0.041, lastCheck: hoursAgo(0.05), affectedOrgs: 3 },
  { name: 'Email delivery', status: 'OPERATIONAL', latencyMs: 320, failureRate: 0.002, lastCheck: hoursAgo(0.1), affectedOrgs: 0 },
  { name: 'SMS (Twilio)', status: 'DEGRADED', latencyMs: 610, failureRate: 0.028, lastCheck: hoursAgo(0.1), affectedOrgs: 2 },
  { name: 'Payments (Stripe)', status: 'OPERATIONAL', latencyMs: 240, failureRate: 0.0, lastCheck: hoursAgo(0.08), affectedOrgs: 0 },
  { name: 'Shopify sync', status: 'PARTIAL_OUTAGE', latencyMs: 42000, failureRate: 0.19, lastCheck: hoursAgo(0.05), affectedOrgs: 3 },
  { name: 'Google APIs', status: 'DEGRADED', latencyMs: 880, failureRate: 0.06, lastCheck: hoursAgo(0.07), affectedOrgs: 1 },
];

export const DEMO_RELEASES = [
  { id: 'rel-41', version: '2026.08.19', stage: 'PRODUCTION', deployedAt: hoursAgo(4), commit: '9bcf0fe', notes: 'Nine-workspace navigation, Customer 360, canonical Settings engine.', status: 'HEALTHY' },
  { id: 'rel-40', version: '2026.08.18', stage: 'PRODUCTION', deployedAt: daysAgo(1), commit: '86ce6b8', notes: 'Credential purge, 27 runtime ReferenceErrors fixed.', status: 'HEALTHY' },
  { id: 'rel-39', version: '2026.08.17', stage: 'PRODUCTION', deployedAt: daysAgo(2), commit: 'ffee340', notes: 'Booking intake, per-store attribution.', status: 'SUPERSEDED' },
  { id: 'rel-38', version: '2026.08.16', stage: 'ROLLED_BACK', deployedAt: daysAgo(3), commit: '6fc5a90', notes: 'Removed marketing.html — root served 502. Rolled back.', status: 'FAILED' },
];

/** Aggregations the Command Center needs. Paying MRR excludes internal/comped and trials. */
export function summarizeOrganizations(orgs: DemoOrganization[] = DEMO_ORGANIZATIONS) {
  const paying = orgs.filter((o) => !o.internal && !o.comped && o.mrrCents > 0);
  const mrrCents = paying.reduce((s, o) => s + o.mrrCents, 0);
  return {
    total: orgs.length,
    active: orgs.filter((o) => o.operationalStatus === 'ACTIVE').length,
    trials: orgs.filter((o) => o.lifecycle === 'TRIAL').length,
    internal: orgs.filter((o) => o.internal || o.comped).length,
    suspended: orgs.filter((o) => o.operationalStatus === 'SUSPENDED').length,
    pastDue: orgs.filter((o) => o.lifecycle === 'PAST_DUE').length,
    atRisk: orgs.filter((o) => o.lifecycle === 'AT_RISK').length,
    inOnboarding: orgs.filter((o) => o.onboardingStatus !== 'COMPLETE').length,
    users: orgs.reduce((s, o) => s + o.userCount, 0),
    locations: orgs.reduce((s, o) => s + o.businesses.reduce((b, x) => b + x.locations.length, 0), 0),
    openTickets: orgs.reduce((s, o) => s + o.openTickets, 0),
    payingCount: paying.length,
    mrrCents,
    arrCents: mrrCents * 12,
  };
}
