/**
 * VowOS Tour Scenario Library
 * Defines 40 structured, robust learning scenarios covering every single tab, card, view, and action in VowOS,
 * plus a continuous Master End-to-End Operational Walkthrough.
 */

export interface TourStepDefinition {
  id: string;
  route: string;
  targetId?: string; // data-tour-id
  mobileTargetId?: string; // mobile specific data-tour-id
  mobileRoute?: string; // mobile specific route
  requiresMobileDrawer?: boolean; // if true, opens the "More" drawer on mobile
  narrationText: string;
  caption: string;
  action: 'explain' | 'move' | 'click' | 'type' | 'select' | 'waitFor' | 'assert';
  value?: string;
  waitForRoute?: string;
}

export interface ScenarioDefinition {
  id: string;
  name: string;
  description: string;
  targetRole: string;
  startRoute: string;
  estimatedMinutes: number;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  steps: TourStepDefinition[];
}

export const DEMO_SCENARIOS: ScenarioDefinition[] = [
  {
    id: 'scenario-0-master-tour',
    name: '0. Master End-to-End Operational Walkthrough',
    description: 'A continuous, uninterrupted deep-dive tour guiding you through every single module, card, tab, and feature in VowOS.',
    targetRole: 'Owner',
    startRoute: 'dashboard',
    estimatedMinutes: 15,
    difficulty: 'Advanced',
    steps: [
      {
        id: 'm0-step1',
        route: 'dashboard',
        targetId: 'hero-banner',
        narrationText: 'Welcome to the VowOS Master Operational Walkthrough. We will start here on the Executive Dashboard, where leadership monitors real-time sales performance and store metrics.',
        caption: 'Master Tour — Executive Dashboard',
        action: 'explain',
      },
      {
        id: 'm0-step2',
        route: 'dashboard',
        targetId: 'stat-revenue',
        narrationText: 'Every stat card on the dashboard features one-touch interactive drilldown capabilities. Let us examine Revenue Collected.',
        caption: 'Drill Down — Revenue Collected',
        action: 'click',
      },
      {
        id: 'm0-step3',
        route: 'dashboard',
        targetId: 'stat-brides',
        narrationText: 'The Active Brides metric provides instant visibility into your current pipeline of active customers preparing for their wedding.',
        caption: 'Review Active Brides',
        action: 'explain',
      },
      {
        id: 'm0-step4',
        route: 'dashboard',
        targetId: 'stat-appointments',
        narrationText: "Track today's appointments at a glance, ensuring your team is fully prepared for upcoming suite fittings.",
        caption: 'Monitor Appointments',
        action: 'explain',
      },
      {
        id: 'm0-step5',
        route: 'customers',
        targetId: 'nav-customers',
        narrationText: 'Next, we move to the Brides CRM roster. Here consultants manage active bride profiles, wedding timelines, and fit preferences.',
        caption: 'Brides CRM Management',
        action: 'click',
        waitForRoute: 'customers',
      },
      {
        id: 'm0-step6',
        route: 'customers',
        targetId: 'search-customers',
        narrationText: 'Instantly search for brides by name, email, or wedding date to access their comprehensive profile and history.',
        caption: 'Search Brides Database',
        action: 'explain',
      },
      {
        id: 'm0-step7',
        route: 'customers',
        targetId: 'table-customers',
        narrationText: 'This centralized table view provides a rapid overview of all active customers and their progression in the bridal lifecycle.',
        caption: 'Active Customers List',
        action: 'explain',
      },
      {
        id: 'm0-step8',
        route: 'customers',
        targetId: 'btn-add-customer',
        narrationText: 'Clicking Add Bride registers a new customer profile and immediately generates a private, secure digital portal link for them.',
        caption: 'Register New Bride Profile',
        action: 'move',
      },
      {
        id: 'm0-step9',
        route: 'leads',
        targetId: 'nav-leads',
        narrationText: 'In Leads Management, incoming bridal inquiries are tracked from initial web contact through consultation booking.',
        caption: 'Leads Pipeline Management',
        action: 'click',
        waitForRoute: 'leads',
      },
      {
        id: 'm0-step10',
        route: 'leads',
        targetId: 'table-leads',
        narrationText: 'The leads table organizes prospects by temperature and engagement level, ensuring no inquiry falls through the cracks.',
        caption: 'Evaluate Lead Pipeline',
        action: 'explain',
      },
      {
        id: 'm0-step11',
        route: 'leads',
        targetId: 'search-leads',
        narrationText: 'Quickly find specific leads to follow up on, using powerful search filters across multiple fields.',
        caption: 'Search Lead Database',
        action: 'explain',
      },
      {
        id: 'm0-step12',
        route: 'leads',
        targetId: 'btn-add-lead',
        narrationText: 'Recording a new phone or walk-in inquiry directly into your sales pipeline is instant with the Add Lead function.',
        caption: 'Record New Lead Inquiry',
        action: 'move',
      },
      {
        id: 'm0-step13',
        route: 'inventory',
        targetId: 'nav-inventory',
        narrationText: 'The Gown Inventory catalog tracks sample dresses, sizes, colors, retail pricing, and store stock levels in real time.',
        caption: 'Gown Inventory Catalog',
        action: 'click',
        waitForRoute: 'inventory',
      },
      {
        id: 'm0-step14',
        route: 'inventory',
        targetId: 'search-inventory',
        narrationText: 'Search by SKU, designer name, or specific sizing to instantly locate available sample inventory across all boutique locations.',
        caption: 'Search Inventory Catalog',
        action: 'explain',
      },
      {
        id: 'm0-step15',
        route: 'inventory',
        targetId: 'table-inventory',
        narrationText: 'Review complete inventory lists including stock levels, variants, and wholesale costs at a glance.',
        caption: 'Review Stock Levels',
        action: 'explain',
      },
      {
        id: 'm0-step16',
        route: 'inventory',
        targetId: 'btn-add-gown',
        narrationText: 'Add Gown introduces new designer sample dresses into the global database with full variations for sizing and colorways.',
        caption: 'Add New Designer Gown',
        action: 'move',
      },
      {
        id: 'm0-step17',
        route: 'transfers',
        targetId: 'nav-transfers',
        narrationText: 'Store Transfers allow seamless inventory sharing between boutique locations for weekend fittings and trunk shows.',
        caption: 'Inter-Store Transfers',
        action: 'click',
        waitForRoute: 'transfers',
      },
      {
        id: 'm0-step18',
        route: 'transfers',
        targetId: 'table-transfers',
        narrationText: 'Monitor all pending, in-transit, and completed transfers to maintain precise control over gown logistics.',
        caption: 'Monitor In-Transit Gowns',
        action: 'explain',
      },
      {
        id: 'm0-step19',
        route: 'transfers',
        targetId: 'btn-request-transfer',
        narrationText: 'Initiating a gown shipment request to another boutique store takes just a few clicks, ensuring logistical transparency.',
        caption: 'Initiate Gown Transfer',
        action: 'move',
      },
      {
        id: 'm0-step20',
        route: 'appointments',
        targetId: 'nav-appointments',
        narrationText: 'In Appointments, suite schedules and stylist coverage calendars ensure every bride receives dedicated personal attention.',
        caption: 'Appointments & Suite Calendar',
        action: 'click',
        waitForRoute: 'appointments',
      },
      {
        id: 'm0-step21',
        route: 'appointments',
        targetId: 'calendar-view-toggle',
        narrationText: 'Toggle seamlessly between daily list views and calendar grids to optimize your spatial awareness of suite bookings.',
        caption: 'Toggle Calendar Views',
        action: 'explain',
      },
      {
        id: 'm0-step22',
        route: 'appointments',
        targetId: 'calendar-grid',
        narrationText: 'The visual calendar allows drag-and-drop rescheduling and instant insights into daily staff coverage.',
        caption: 'Visual Calendar Grid',
        action: 'explain',
      },
      {
        id: 'm0-step23',
        route: 'appointments',
        targetId: 'btn-book-appointment',
        narrationText: 'Reserving a private fitting suite and assigning a dedicated consultant is streamlined through the booking engine.',
        caption: 'Book New Bridal Suite Visit',
        action: 'move',
      },
      {
        id: 'm0-step24',
        route: 'timeclock',
        targetId: 'nav-timeclock',
        narrationText: 'The Time Clock Kiosk enables store staff to clock in, log breaks, and switch store locations securely.',
        caption: 'Time Clock & Staff Kiosk',
        action: 'click',
        waitForRoute: 'timeclock',
      },
      {
        id: 'm0-step25',
        route: 'timeclock',
        targetId: 'btn-clock-in',
        narrationText: 'Staff can log their shift start instantly, ensuring accurate payroll calculation and compliance with labor regulations.',
        caption: 'Clock In For Shift',
        action: 'explain',
      },
      {
        id: 'm0-step26',
        route: 'timeclock',
        targetId: 'btn-clock-out',
        narrationText: 'Clocking out securely records the end of shift, closing the timecard entry for payroll processing.',
        caption: 'Clock Out From Shift',
        action: 'explain',
      },
      {
        id: 'm0-step27',
        route: 'timeclock',
        targetId: 'btn-start-break',
        narrationText: 'Staff can easily log lunch or rest breaks to maintain labor law compliance and accurate paid hours.',
        caption: 'Log Staff Breaks',
        action: 'explain',
      },
      {
        id: 'm0-step28',
        route: 'communications',
        targetId: 'nav-communications',
        narrationText: 'Communications provides a unified SMS and email messaging center for automated appointment reminders and gown updates.',
        caption: 'Communications & Messaging Hub',
        action: 'click',
        waitForRoute: 'communications',
      },
      {
        id: 'm0-step29',
        route: 'communications',
        targetId: 'list-messages',
        narrationText: 'The central inbox consolidates all ongoing conversations, ensuring prompt responses and excellent customer service.',
        caption: 'Unified Inbox view',
        action: 'explain',
      },
      {
        id: 'm0-step30',
        route: 'communications',
        targetId: 'btn-new-message',
        narrationText: 'Drafting a direct, personalized message to a bride from the unified hub ensures a premium, high-touch communication standard.',
        caption: 'Compose New Message',
        action: 'explain',
      },
      {
        id: 'm0-step31',
        route: 'communications',
        targetId: 'btn-run-automations',
        narrationText: 'Automated sequences dispatch tailored reminders to upcoming appointments, drastically reducing no-show rates and recovering lost revenue.',
        caption: 'Run Automation Sequences',
        action: 'explain',
      },
      {
        id: 'm0-step32',
        route: 'communications',
        targetId: 'btn-magic-reply',
        narrationText: 'The built-in AI Magic Reply reads the conversation context and instantly drafts perfectly toned responses to incoming customer queries.',
        caption: 'Draft AI Magic Reply',
        action: 'explain',
      },
      {
        id: 'm0-step33',
        route: 'communications',
        targetId: 'template-chip-pickup',
        narrationText: 'Use pre-approved templates for routine updates like gown pickups, maintaining brand consistency across your team.',
        caption: 'Use Brand Templates',
        action: 'explain',
      },
      {
        id: 'm0-step34',
        route: 'contracts',
        targetId: 'nav-contracts',
        narrationText: 'Contracts allows brides to review digital purchase agreements and complete electronic signature sign-offs natively within VowOS.',
        caption: 'Electronic Signature Contracts',
        action: 'click',
        waitForRoute: 'contracts',
      },
      {
        id: 'm0-step35',
        route: 'contracts',
        targetId: 'table-contracts',
        narrationText: 'Track the status of all agreements, instantly seeing which are signed, pending, or awaiting review.',
        caption: 'Track Contract Status',
        action: 'explain',
      },
      {
        id: 'm0-step36',
        route: 'contracts',
        targetId: 'btn-new-contract',
        narrationText: 'Drafting a new digital agreement is fast, ensuring compliance and crystal-clear terms of sale for gown purchases.',
        caption: 'Draft New Contract',
        action: 'explain',
      },
      {
        id: 'm0-step37',
        route: 'alterations',
        targetId: 'nav-alterations',
        narrationText: 'The Alterations module tracks fitting tickets, seamstress work queues, due dates, and gown pickup sign-offs.',
        caption: 'Alterations & Fitting Tickets',
        action: 'click',
        waitForRoute: 'alterations',
      },
      {
        id: 'm0-step38',
        route: 'alterations',
        targetId: 'table-alterations',
        narrationText: 'Monitor the progress of every gown undergoing alterations to guarantee on-time completion for the wedding day.',
        caption: 'Monitor Seamstress Queue',
        action: 'explain',
      },
      {
        id: 'm0-step39',
        route: 'alterations',
        targetId: 'btn-new-fitting',
        narrationText: 'Scheduling a new fitting captures hem, bustle, and bodice adjustment requirements directly into the seamstress production queue.',
        caption: 'Schedule New Fitting',
        action: 'explain',
      },
      {
        id: 'm0-step40',
        route: 'invoices',
        targetId: 'nav-invoices',
        narrationText: 'Point of Sale & Invoices processes gown deposits, split-tender payments, and final balance collections.',
        caption: 'Point of Sale & Invoices',
        action: 'click',
        waitForRoute: 'invoices',
      },
      {
        id: 'm0-step41',
        route: 'invoices',
        targetId: 'table-invoices',
        narrationText: 'The central invoice table provides a complete audit trail of pending balances and fully settled accounts.',
        caption: 'Audit Pending Balances',
        action: 'explain',
      },
      {
        id: 'm0-step42',
        route: 'invoices',
        targetId: 'btn-pay-inv-2',
        narrationText: 'When a bride returns to pay her remaining balance, the Record Payment workflow handles multi-tender splits natively.',
        caption: 'Record Outstanding Payment',
        action: 'explain',
      },
      {
        id: 'm0-step43',
        route: 'invoices',
        targetId: 'btn-new-invoice',
        narrationText: 'Generating a new invoice translates a final gown selection into a legally binding financial record.',
        caption: 'Create New Invoice',
        action: 'explain',
      },
      {
        id: 'm0-step44',
        route: 'purchases',
        targetId: 'nav-purchases',
        narrationText: 'Purchase Orders tracks designer orders, vendor portal credentials, and factory delivery lead times.',
        caption: 'Purchase Orders & Vendor Vault',
        action: 'click',
        waitForRoute: 'purchases',
      },
      {
        id: 'm0-step45',
        route: 'purchases',
        targetId: 'table-purchases',
        narrationText: 'Stay ahead of factory delays by tracking estimated shipping dates and order statuses in real-time.',
        caption: 'Track Order Status',
        action: 'explain',
      },
      {
        id: 'm0-step46',
        route: 'purchases',
        targetId: 'btn-vendor-vault',
        narrationText: 'The Vendor Credentials Vault securely stores website URLs, usernames, and passwords for streamlined external ordering.',
        caption: 'Access Vendor Vault',
        action: 'explain',
      },
      {
        id: 'm0-step47',
        route: 'purchases',
        targetId: 'btn-new-po',
        narrationText: 'Issuing a new purchase order synchronizes store demand with factory production timelines effectively.',
        caption: 'Issue New Purchase Order',
        action: 'explain',
      },
      {
        id: 'm0-step48',
        route: 'marketing',
        targetId: 'nav-marketing',
        narrationText: 'The Growth & Marketing Command Center connects Meta, Google, and TikTok ad accounts, providing automated ROAS tracking and AI-driven insights.',
        caption: 'Growth Command Center',
        action: 'click',
        waitForRoute: 'marketing',
      },
      {
        id: 'm0-step49',
        route: 'marketing',
        targetId: 'chart-roas',
        narrationText: 'Visualize Return on Ad Spend (ROAS) across platforms to optimize your marketing budget allocation.',
        caption: 'Visualize ROAS Metrics',
        action: 'explain',
      },
      {
        id: 'm0-step50',
        route: 'marketing',
        targetId: 'btn-new-campaign',
        narrationText: 'Launch structured marketing campaigns targeted specifically at engaged brides in your local area.',
        caption: 'Launch New Campaign',
        action: 'explain',
      },
      {
        id: 'm0-step51',
        route: 'reports',
        targetId: 'nav-reports',
        narrationText: 'Insights & Reports deliver executive-grade business intelligence across multiple dimensions of store performance.',
        caption: 'Store Performance Reports',
        action: 'click',
        waitForRoute: 'reports',
      },
      {
        id: 'm0-step52',
        route: 'reports',
        targetId: 'tab-report-range',
        narrationText: 'Sales by Date Range analysis enables strategic evaluation of seasonal trends and promotional efficacy.',
        caption: 'Evaluate Seasonal Trends',
        action: 'explain',
      },
      {
        id: 'm0-step53',
        route: 'reports',
        targetId: 'tab-report-goals',
        narrationText: 'Sales Goals tracking translates top-line revenue into actionable individual consultant performance quotas.',
        caption: 'Monitor Staff Quotas',
        action: 'explain',
      },
      {
        id: 'm0-step54',
        route: 'reports',
        targetId: 'chart-sales',
        narrationText: 'Interactive charts visualize key performance indicators, making complex data easily digestible.',
        caption: 'Visualize Key Metrics',
        action: 'explain',
      },
      {
        id: 'm0-step55',
        route: 'reports',
        targetId: 'btn-ai-analyze',
        narrationText: 'Our AI Copilot rapidly cross-references millions of data points to generate actionable insights in seconds.',
        caption: 'Run AI Trend Analysis',
        action: 'explain',
      },
      {
        id: 'm0-step56',
        route: 'reports',
        targetId: 'ai-copilot-panel',
        narrationText: 'The Copilot instantly produces a concise digest on revenue, inventory, and staff trends without manual spreadsheet work.',
        caption: 'Review AI Insights',
        action: 'explain',
      },
      {
        id: 'm0-step57',
        route: 'ledgers',
        targetId: 'nav-ledgers',
        narrationText: 'Financial Ledgers provide a granular, compliant breakdown of all debits, credits, and deposits across the business.',
        caption: 'Financial Ledgers',
        action: 'click',
        waitForRoute: 'ledgers',
      },
      {
        id: 'm0-step58',
        route: 'ledgers',
        targetId: 'tabs-ledgers',
        narrationText: 'Switching between accounts payable, accounts receivable, and localized deposits is instantaneous via the ledger tabs.',
        caption: 'Navigate Ledger Tabs',
        action: 'explain',
      },
      {
        id: 'm0-step59',
        route: 'ledgers',
        targetId: 'table-ledgers',
        narrationText: 'A precise, auditable transaction log ensures absolute financial integrity and simplifies accounting workflows.',
        caption: 'Audit Transaction Log',
        action: 'explain',
      },
      {
        id: 'm0-step60',
        route: 'staff',
        targetId: 'nav-staff',
        narrationText: 'Staff & Roles manages employee directories, access controls, role assignments, and granular per-user permissions.',
        caption: 'Staff & Access Control',
        action: 'click',
        waitForRoute: 'staff',
      },
      {
        id: 'm0-step61',
        route: 'staff',
        targetId: 'table-staff',
        narrationText: 'View the active roster of employees, their assigned roles, and recent activity logs at a glance.',
        caption: 'View Employee Roster',
        action: 'explain',
      },
      {
        id: 'm0-step62',
        route: 'staff',
        targetId: 'btn-add-staff',
        narrationText: 'Inviting new team members automatically handles provisioning and sets precise security access boundaries.',
        caption: 'Onboard New Staff',
        action: 'explain',
      },
      {
        id: 'm0-step63',
        route: 'payroll',
        targetId: 'nav-payroll',
        narrationText: 'Payroll features a complete workforce management suite covering timecards, exceptions, and direct deposit batching.',
        caption: 'Payroll & Workforce Command',
        action: 'click',
        waitForRoute: 'payroll',
      },
      {
        id: 'm0-step64',
        route: 'payroll',
        targetId: 'tabs-payroll',
        narrationText: 'The tabular interface segments the payroll workflow into logical steps, preventing errors during batch processing.',
        caption: 'Navigate Payroll Workflow',
        action: 'explain',
      },
      {
        id: 'm0-step65',
        route: 'payroll',
        targetId: 'payroll-summary-cards',
        narrationText: 'Top-level summary cards provide instant visibility into estimated gross payroll and pending exception flags.',
        caption: 'Review Payroll Summaries',
        action: 'explain',
      },
      {
        id: 'm0-step66',
        route: 'payroll',
        targetId: 'table-payroll',
        narrationText: 'Detailed timecard views allow managers to verify hours worked, commissions earned, and deductions applied.',
        caption: 'Verify Detailed Timecards',
        action: 'explain',
      },
      {
        id: 'm0-step67',
        route: 'payroll',
        targetId: 'tab-payroll-exceptions',
        narrationText: 'The Exception Center automatically flags missed punches and overtime risks for review prior to processing.',
        caption: 'Audit Timecard Exceptions',
        action: 'explain',
      },
      {
        id: 'm0-step68',
        route: 'payroll',
        targetId: 'btn-run-payroll',
        narrationText: 'Executing a batch run securely calculates wages, applies tax withholdings, and preps the final banking file for submission.',
        caption: 'Execute Multi-Store Payroll',
        action: 'explain',
      },
      {
        id: 'm0-step69',
        route: 'settings',
        targetId: 'nav-settings',
        narrationText: 'Corporate Settings centralize boutique operations, booking rules, communication templates, and security audits.',
        caption: 'Corporate Settings & Config',
        action: 'click',
        waitForRoute: 'settings',
      },
      {
        id: 'm0-step70',
        route: 'settings',
        targetId: 'tabs-settings',
        narrationText: 'The configuration tabs separate operational areas, ensuring complex system rules remain easily accessible and manageable.',
        caption: 'Navigate Configuration Panels',
        action: 'explain',
      },
      {
        id: 'm0-step71',
        route: 'settings',
        targetId: 'card-settings-active',
        narrationText: 'Security audit logs record every sensitive setting change, login event, and permission modification.',
        caption: 'Audit System Security',
        action: 'explain',
      },
    ],
  },
  {
    id: 'scenario-owner-overview',
    name: '1. Executive Dashboard & KPI Drilldowns',
    description: 'Explore total revenue collected, outstanding balances, active bride counts, and multi-store KPIs.',
    targetRole: 'Owner',
    startRoute: 'dashboard',
    estimatedMinutes: 3,
    difficulty: 'Beginner',
    steps: [
      {
        id: 's1-step1',
        route: 'dashboard',
        targetId: 'hero-banner',
        narrationText: 'Welcome to VowOS. As an Owner, your Executive Dashboard gives you an instant real-time snapshot of revenue, outstanding balances, active brides, and gown inventory.',
        caption: 'Explore Executive Dashboard KPIs',
        action: 'explain',
      },
      {
        id: 's1-step2',
        route: 'dashboard',
        targetId: 'stat-revenue',
        narrationText: 'Clicking on Revenue Collected opens an itemized drilldown ledger showing every paid invoice across all boutique locations.',
        caption: 'Drill down into Revenue Collected',
        action: 'click',
      },
      {
        id: 's1-step3',
        route: 'dashboard',
        targetId: 'stat-brides',
        narrationText: 'Notice how every metric offers one-touch interactive drilldown access right to source customer records.',
        caption: 'Review Active Brides roster',
        action: 'click',
      },
    ],
  },
  {
    id: 'scenario-bride-crm',
    name: '2. Active Brides CRM & Fit Profile Roster',
    description: 'Manage active bride profiles, wedding dates, assigned stylists, and fit profile measurements.',
    targetRole: 'Bridal Consultant',
    startRoute: 'customers',
    estimatedMinutes: 4,
    difficulty: 'Beginner',
    steps: [
      {
        id: 's2-step1',
        route: 'customers',
        targetId: 'nav-customers',
        narrationText: 'In the Brides CRM, consultants view active wedding timelines, budgets, and assigned stylists.',
        caption: 'Open Brides CRM',
        action: 'click',
        waitForRoute: 'customers',
      },
      {
        id: 's2-step2',
        route: 'customers',
        targetId: 'search-customers',
        narrationText: 'You can instantly search for brides by name, email, or wedding date.',
        caption: 'Search Brides Database',
        action: 'explain',
      },
      {
        id: 's2-step3',
        route: 'customers',
        targetId: 'btn-add-customer',
        narrationText: 'Clicking Add Bride registers a new customer profile and generates a private digital portal link.',
        caption: 'Register New Bride Profile',
        action: 'move',
      },
    ],
  },
  {
    id: 'scenario-lead-pipeline',
    name: '3. Lead Ingestion & Qualification Engine',
    description: 'Track incoming bridal web leads, intake questions, and booking conversion stages.',
    targetRole: 'Front Desk',
    startRoute: 'leads',
    estimatedMinutes: 3,
    difficulty: 'Beginner',
    steps: [
      {
        id: 's3-step1',
        route: 'leads',
        targetId: 'nav-leads',
        narrationText: 'Leads Management captures prospective brides inquiring online through website forms or social channels.',
        caption: 'Navigate to Leads Management',
        action: 'click',
        waitForRoute: 'leads',
      },
      {
        id: 's3-step2',
        route: 'leads',
        targetId: 'btn-add-lead',
        narrationText: 'Clicking Add Lead records new phone or walk-in inquiries directly into your sales pipeline.',
        caption: 'Record New Lead Inquiry',
        action: 'explain',
      },
    ],
  },
  {
    id: 'scenario-gown-inventory',
    name: '4. Gown Catalog & Sample Inventory Controls',
    description: 'Manage sample dresses, size/color variants, retail pricing, and reorder alerts.',
    targetRole: 'Inventory',
    startRoute: 'inventory',
    estimatedMinutes: 4,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's4-step1',
        route: 'inventory',
        targetId: 'nav-inventory',
        narrationText: 'Gown Inventory maintains real-time sample dress stock, wholesale costs, retail prices, and location counts.',
        caption: 'Open Gown Inventory',
        action: 'click',
        waitForRoute: 'inventory',
      },
      {
        id: 's4-step2',
        route: 'inventory',
        targetId: 'search-inventory',
        narrationText: 'Use the search bar to locate specific designer gowns, SKUs, or sample sizes across all stores.',
        caption: 'Search Inventory Catalog',
        action: 'explain',
      },
      {
        id: 's4-step3',
        route: 'inventory',
        targetId: 'btn-add-gown',
        narrationText: 'Click Add Gown to introduce new designer sample dresses to your inventory database.',
        caption: 'Add New Designer Gown',
        action: 'move',
      },
    ],
  },
  {
    id: 'scenario-store-transfers',
    name: '5. Inter-Store Stock Transfers & Logistics',
    description: 'Transfer sample gowns between boutique locations for trunk shows and fittings.',
    targetRole: 'Inventory',
    startRoute: 'transfers',
    estimatedMinutes: 4,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's5-step1',
        route: 'transfers',
        targetId: 'nav-transfers',
        narrationText: 'Store Transfers manages in-transit gowns moving between your flagship and suburban boutique locations.',
        caption: 'Open Store Transfers',
        action: 'click',
        waitForRoute: 'transfers',
      },
      {
        id: 's5-step2',
        route: 'transfers',
        targetId: 'btn-request-transfer',
        narrationText: 'Click New Transfer to initiate a gown shipment request to another boutique store.',
        caption: 'Initiate Gown Transfer',
        action: 'click',
      },
    ],
  },
  {
    id: 'scenario-calendar-appointments',
    name: '6. Suite Scheduling & Calendar Coverage',
    description: 'Schedule private bridal suites, assign consultants, and manage fitting appointments.',
    targetRole: 'Store Manager',
    startRoute: 'appointments',
    estimatedMinutes: 5,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's6-step1',
        route: 'appointments',
        targetId: 'nav-appointments',
        narrationText: 'The Appointments Calendar provides view switching between calendar grids and itemized daily lists.',
        caption: 'Open Appointments Calendar',
        action: 'click',
        waitForRoute: 'appointments',
      },
      {
        id: 's6-step2',
        route: 'appointments',
        targetId: 'btn-book-appointment',
        narrationText: 'Click Book Appointment to reserve a private fitting suite and assign a dedicated consultant.',
        caption: 'Book New Bridal Suite Visit',
        action: 'move',
      },
    ],
  },
  {
    id: 'scenario-timeclock-kiosk',
    name: '7. Time Clock & Store Kiosk Station',
    description: 'Clock in, select store location, record breaks, and log employee shifts.',
    targetRole: 'Stylist',
    startRoute: 'timeclock',
    estimatedMinutes: 3,
    difficulty: 'Beginner',
    steps: [
      {
        id: 's7-step1',
        route: 'timeclock',
        targetId: 'nav-timeclock',
        narrationText: 'The Time Clock Kiosk is the touch-friendly station used by store staff to clock in and out daily.',
        caption: 'Open Time Clock Kiosk',
        action: 'click',
        waitForRoute: 'timeclock',
      },
    ],
  },
  {
    id: 'scenario-messaging-hub',
    name: '8. Customer Communications & Messaging Hub',
    description: 'Deploy targeted SMS/Email campaigns, use AI Magic Reply for instant drafts, and run automated follow-up sequences.',
    targetRole: 'Front Desk',
    startRoute: 'communications',
    estimatedMinutes: 5,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's8-step1',
        route: 'communications',
        targetId: 'nav-communications',
        narrationText: 'The Omnichannel Communications Hub centralizes SMS and email. Rather than jumping between apps, you communicate with brides directly from their core record.',
        caption: 'Open Communications Hub',
        action: 'click',
        waitForRoute: 'communications',
      },
      {
        id: 's8-step2',
        route: 'communications',
        targetId: 'btn-run-automations',
        narrationText: 'Automations can instantly dispatch tailored reminders to upcoming appointments, reducing no-shows and driving revenue.',
        caption: 'Run Automation Sequences',
        action: 'click',
      },
      {
        id: 's8-step3',
        route: 'communications',
        targetId: 'btn-magic-reply',
        narrationText: 'The built-in AI Magic Reply reads the conversation context and instantly drafts perfectly toned responses to customer questions.',
        caption: 'Draft AI Magic Reply',
        action: 'click',
      },
      {
        id: 's8-step4',
        route: 'communications',
        targetId: 'template-chip-pickup',
        narrationText: 'Standardized templates ensure your entire team maintains a consistent, premium brand voice for routine notifications.',
        caption: 'Apply Brand Templates',
        action: 'click',
      },
    ],
  },
  {
    id: 'scenario-contracts-esign',
    name: '9. Electronic Contracts & Digital Signatures',
    description: 'Issue gown purchase agreements, review terms of sale, and collect e-signatures.',
    targetRole: 'Front Desk',
    startRoute: 'contracts',
    estimatedMinutes: 4,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's9-step1',
        route: 'contracts',
        targetId: 'nav-contracts',
        narrationText: 'In Contracts, digital sales agreements are emailed or texted to brides for instant initialing and signing.',
        caption: 'Open Electronic Contracts',
        action: 'click',
        waitForRoute: 'contracts',
      },
    ],
  },
  {
    id: 'scenario-alterations-queue',
    name: '10. Alterations Tickets & Fitting Work Queue',
    description: 'Track alteration fittings, hem/bustle tasks, seamstress assignments, and pickup dates.',
    targetRole: 'Seamstress',
    startRoute: 'alterations',
    estimatedMinutes: 5,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's10-step1',
        route: 'alterations',
        targetId: 'nav-alterations',
        narrationText: 'The Alterations Center manages fitting tickets, seamstress assignments, and scheduled pickup due dates.',
        caption: 'Open Alterations Center',
        action: 'click',
        waitForRoute: 'alterations',
      },
    ],
  },
  {
    id: 'scenario-pos-invoices',
    name: '11. Checkout, POS & Payment Splits',
    description: 'Process multi-tender payments, manage partial deposit collections, and finalize balance collections.',
    targetRole: 'Front Desk',
    startRoute: 'invoices',
    estimatedMinutes: 5,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's11-step1',
        route: 'invoices',
        targetId: 'nav-invoices',
        narrationText: 'The Point of Sale system is deeply integrated with the Bridal CRM. It handles split payments, deposits, and final balance collections effortlessly.',
        caption: 'Open Point of Sale Station',
        action: 'click',
        waitForRoute: 'invoices',
      },
      {
        id: 's11-step2',
        route: 'invoices',
        targetId: 'btn-pay-inv-2',
        narrationText: 'When a bride returns to pay her remaining balance, the Record Payment workflow handles multi-tender splits natively.',
        caption: 'Record Outstanding Payment',
        action: 'click',
      },
    ],
  },
  {
    id: 'scenario-purchasing-vault',
    name: '12. Purchase Orders & Vendor Vault Credentials',
    description: 'Manage vendor purchase orders, store designer credentials in vault, and track gown ETAs.',
    targetRole: 'Purchasing',
    startRoute: 'purchases',
    estimatedMinutes: 4,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's12-step1',
        route: 'purchases',
        targetId: 'nav-purchases',
        narrationText: 'Purchase Orders manages designer gown orders, estimated delivery dates, and vendor website logins.',
        caption: 'Open Purchase Orders',
        action: 'click',
        waitForRoute: 'purchases',
      },
      {
        id: 's12-step2',
        route: 'purchases',
        targetId: 'btn-vendor-vault',
        narrationText: 'The Vendor Credentials Vault securely stores website URLs, usernames, and passwords for ordering portals.',
        caption: 'Access Vendor Vault Credentials',
        action: 'click',
      },
    ],
  },
  {
    id: 'scenario-reports-analytics',
    name: '13. Reporting & Business Intelligence',
    description: 'Deep dive into revenue reporting, sales by date range, staff performance quotas, and the new AI Copilot trend analysis.',
    targetRole: 'Owner',
    startRoute: 'reports',
    estimatedMinutes: 6,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's13-step1',
        route: 'reports',
        targetId: 'nav-reports',
        narrationText: 'The VowOS Reporting suite delivers executive-grade business intelligence. Here, we track real-time revenue comparisons across all boutique locations.',
        caption: 'Open Business Intelligence',
        action: 'click',
        waitForRoute: 'reports',
      },
      {
        id: 's13-step2',
        route: 'reports',
        targetId: 'tab-report-range',
        narrationText: 'Switching to the Sales by Date tab allows us to analyze performance over specific seasonal periods.',
        caption: 'View Sales by Date Range',
        action: 'click',
      },
      {
        id: 's13-step3',
        route: 'reports',
        targetId: 'tab-report-goals',
        narrationText: 'The Sales Goals tab tracks individual consultant quotas, converting data into actionable staff performance metrics.',
        caption: 'Monitor Staff Performance',
        action: 'click',
      },
      {
        id: 's13-step4',
        route: 'reports',
        targetId: 'btn-ai-analyze',
        narrationText: 'And with the new AI Copilot, you can instantly generate a cross-referenced trend analysis to surface hidden opportunities in your data.',
        caption: 'Run AI Trend Analysis',
        action: 'click',
      },
      {
        id: 's13-step5',
        route: 'reports',
        targetId: 'ai-copilot-panel',
        narrationText: 'The Copilot instantly reads through millions of data points, producing a concise digest on revenue, inventory, and staff trends without manual spreadsheet work.',
        caption: 'Review AI Insights',
        action: 'explain',
      },
    ],
  },
  {
    id: 'scenario-financial-ledger',
    name: '14. Financial General Ledger & Payment Audit',
    description: 'Audit cash flow, transaction history, deposit collections, and general ledgers.',
    targetRole: 'Owner',
    startRoute: 'ledgers',
    estimatedMinutes: 4,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's14-step1',
        route: 'ledgers',
        targetId: 'nav-ledgers',
        narrationText: 'Ledgers provides a complete accounting breakdown of debits, credits, deposits, and payment reconciliations.',
        caption: 'Open Financial Ledgers',
        action: 'click',
        waitForRoute: 'ledgers',
      },
    ],
  },
  {
    id: 'scenario-staff-approval',
    name: '15. Staff Onboarding & Approval Machine',
    description: 'Review pending staff account registrations, assign roles, and grant section permissions.',
    targetRole: 'Manager',
    startRoute: 'staff',
    estimatedMinutes: 4,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's15-step1',
        route: 'staff',
        targetId: 'nav-staff',
        narrationText: 'In Staff & Roles, administrators approve new staff registrations and manage access roles across VowOS.',
        caption: 'Open Staff & Roles',
        action: 'click',
        waitForRoute: 'staff',
      },
      {
        id: 's15-step2',
        route: 'staff',
        targetId: 'btn-add-staff',
        narrationText: 'Clicking Add Staff Member invites new team members with custom role permissions.',
        caption: 'Add New Staff Member',
        action: 'move',
      },
    ],
  },
  {
    id: 'scenario-payroll-wizard',
    name: '16. Payroll & Workforce Management',
    description: 'Manage staff compensation, resolve timecard exceptions, run multi-store payroll batches, and authorize direct deposits.',
    targetRole: 'Payroll Administrator',
    startRoute: 'payroll',
    estimatedMinutes: 6,
    difficulty: 'Advanced',
    steps: [
      {
        id: 's16-step1',
        route: 'payroll',
        targetId: 'nav-payroll',
        narrationText: 'The Workforce Management suite consolidates timecards, wage rates, and payroll processing into a single compliant hub.',
        caption: 'Open Workforce Management',
        action: 'click',
        waitForRoute: 'payroll',
      },
      {
        id: 's16-step2',
        route: 'payroll',
        targetId: 'tab-payroll-compensation',
        narrationText: 'The Compensation & Rates tab allows administrators to manage hourly tiers and salaried staff profiles securely.',
        caption: 'View Compensation Profiles',
        action: 'click',
      },
      {
        id: 's16-step3',
        route: 'payroll',
        targetId: 'tab-payroll-exceptions',
        narrationText: 'Before running payroll, the Exception Center automatically flags missed punches and overtime risks for review.',
        caption: 'Audit Timecard Exceptions',
        action: 'click',
      },
      {
        id: 's16-step4',
        route: 'payroll',
        targetId: 'tab-payroll-command',
        narrationText: 'Once exceptions are cleared, we return to the Command Center to execute the final payroll batch.',
        caption: 'Return to Command Center',
        action: 'click',
      },
      {
        id: 's16-step5',
        route: 'payroll',
        targetId: 'btn-run-payroll-scope',
        narrationText: 'Running the batch securely calculates gross wages, tax withholdings, and prepares direct deposit files for your bank.',
        caption: 'Execute Payroll Batch',
        action: 'click',
      },
    ],
  },
  {
    id: 'scenario-training-certification',
    name: '17. Training Center & Role Certification',
    description: 'Access role-based learning curricula, completed scenario history, and certification status.',
    targetRole: 'Stylist',
    startRoute: 'training',
    estimatedMinutes: 3,
    difficulty: 'Beginner',
    steps: [
      {
        id: 's17-step1',
        route: 'training',
        targetId: 'nav-training',
        narrationText: 'The VowOS Training Center provides voice-guided interactive tours and hands-on scenario certifications for all store roles.',
        caption: 'Open Training Center',
        action: 'click',
        waitForRoute: 'training',
      },
      {
        id: 's17-step2',
        route: 'training',
        targetId: 'tabs-training-roles',
        narrationText: 'Filter scenarios by role to focus on tasks specific to Owners, Managers, Consultants, or Payroll Admins.',
        caption: 'Filter Training Scenarios',
        action: 'explain',
      },
    ],
  },
  {
    id: 'scenario-settings-org',
    name: '18. System Settings & Location Configurations',
    description: 'Configure corporate parameters, boutique operating hours, payment gateway options, and security rules.',
    targetRole: 'Owner',
    startRoute: 'settings',
    estimatedMinutes: 4,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 's18-step1',
        route: 'settings',
        targetId: 'nav-settings',
        narrationText: 'Settings provides central management for corporate branding, store hours, payment surcharges, and security settings.',
        caption: 'Open Corporate Settings',
        action: 'click',
        waitForRoute: 'settings',
      },
      {
        id: 's18-step2',
        route: 'settings',
        targetId: 'tabs-settings',
        narrationText: 'Use the left navigation menu to navigate between 22 specialized settings panels.',
        caption: 'Navigate Settings Panels',
        action: 'explain',
      },
    ],
  },
];

// Add scenarios 19 through 39 with full continuous definitions
const ADDITIONAL_SCENARIOS: { name: string; desc: string; role: string; route: string; target: string; narration: string; caption: string }[] = [
  { name: '19. Customer Fit Profile & Measurements', desc: 'Record bride bust, waist, hips, and height measurements for gown sizing.', role: 'Stylist', route: 'customers', target: 'search-customers', narration: 'In the bride profile, consultants enter accurate fitting measurements to select optimal gown sizes.', caption: 'Manage Fit Profiles' },
  { name: '20. Bride Portal Experience & Document Access', desc: 'Preview the bride’s digital portal, contract copies, and payment history.', role: 'Stylist', route: 'customers', target: 'table-customers', narration: 'Every bride receives a personal portal link to review their contract, pay balances, and track gown progress.', caption: 'Preview Bride Digital Portal' },
  { name: '21. Public Online Suite Booking Flow', desc: 'Demonstrate how prospective brides book private suites online.', role: 'Front Desk', route: 'appointments', target: 'btn-booking-qr', narration: 'Brides scan QR codes in-store or visit your website to book private fitting suites with instant confirmation.', caption: 'Public Online Suite Booking' },
  { name: '22. Handling Customer Appointment Reschedules', desc: 'Reschedule fitting dates and update stylist suite assignments.', role: 'Front Desk', route: 'appointments', target: 'calendar-view-switcher', narration: 'When a bride calls to reschedule, front desk staff move the appointment on the calendar grid.', caption: 'Reschedule Fitting Visit' },
  { name: '23. Managing Cancellations & Deposit Refunds', desc: 'Process appointment cancellations and manage fee retention policies.', role: 'Front Desk', route: 'appointments', target: 'nav-appointments', narration: 'Cancellations update calendar suite availability and log transaction records for financial audit.', caption: 'Process Cancellation' },
  { name: '24. Building Custom Bride Favorites List', desc: 'Curate a list of preferred designer dresses prior to bridal consultation.', role: 'Stylist', route: 'inventory', target: 'search-inventory', narration: 'Consultants build personalized gown try-on lists based on bride preferences and style notes.', caption: 'Curate Gown Try-on List' },
  { name: '25. Converting Quote to Official Invoice', desc: 'Transform a dress price quote into an official purchase invoice.', role: 'Bridal Consultant', route: 'invoices', target: 'nav-invoices', narration: 'Converting a quote to an invoice locks in gown pricing and initiates factory ordering.', caption: 'Convert Quote to Sales Invoice' },
  { name: '26. Resolving Vendor PO Delivery Discrepancies', desc: 'Flag shipping delays, partial shipments, and update expected ETAs.', role: 'Purchasing', route: 'purchases', target: 'btn-new-po', narration: 'Purchasing staff update factory shipping statuses and alert consultants of any delivery changes.', caption: 'Resolve PO Shipping Delay' },
  { name: '27. Store-to-Store Transit Receiving & QC', desc: 'Receive inbound store transfers and log quality control inspections.', role: 'Inventory', route: 'transfers', target: 'btn-request-transfer', narration: 'Receiving staff inspect transferred gowns upon arrival and update store stock quantities.', caption: 'Receive & Inspect Transfer' },
  { name: '28. Handling Damaged Goods & Return Approvals', desc: 'Log damaged gown items and issue vendor return authorizations.', role: 'Inventory', route: 'inventory', target: 'search-inventory', narration: 'Damaged or defective sample dresses are flagged for vendor repair or credit adjustment.', caption: 'Log Damaged Stock Item' },
  { name: '29. Second Fitting & Quality Inspection', desc: 'Perform second fitting review and verify alteration hem/bustle accuracy.', role: 'Seamstress', route: 'alterations', target: 'nav-alterations', narration: 'During second fittings, seamstresses verify fit perfection before releasing the gown for final press.', caption: 'Second Fitting Signoff' },
  { name: '30. Gown Final Inspection & Pickup Signoff', desc: 'Complete final inspection signoff and mark gown ready for bride pickup.', role: 'Seamstress', route: 'alterations', target: 'nav-alterations', narration: 'Final inspection confirms dress pressing, steaming, and accessory packing prior to bride pickup.', caption: 'Final Pickup Signoff' },
  { name: '31. Employee Timecard Correction Requests', desc: 'Submit timecard adjustment requests for missing punches.', role: 'Stylist', route: 'timeclock', target: 'nav-timeclock', narration: 'Employees submit correction notes if they forget to clock in or out during shift transitions.', caption: 'Submit Punch Correction' },
  { name: '32. Approving Store Staff Timecards', desc: 'Review weekly staff hours, verify break logs, and approve timecards.', role: 'Store Manager', route: 'payroll', target: 'tabs-payroll', narration: 'Store managers audit shift duration, lunch breaks, and overtime before approving timecard logs.', caption: 'Approve Weekly Timecards' },
  { name: '33. Awarding Monthly Sales Bonuses & Commissions', desc: 'Calculate consultant commission tiers and award sales milestone bonuses.', role: 'Store Manager', route: 'payroll', target: 'payroll-summary-cards', narration: 'VowOS automatically calculates consultant commission percentages based on gown sales performance.', caption: 'Calculate Commissions & Bonuses' },
  { name: '34. Multi-Store Payroll Batch Run', desc: 'Execute multi-store payroll batch run and generate direct deposit files.', role: 'Payroll Administrator', route: 'payroll', target: 'btn-run-payroll', narration: 'Payroll administrators execute batch runs across all boutique locations in a single click.', caption: 'Multi-Store Payroll Batch' },
  { name: '35. Resolving Payroll Exceptions & Missing Punches', desc: 'Audit geofence breaches and fix unclosed employee clock-in punches.', role: 'Payroll Administrator', route: 'payroll', target: 'tabs-payroll', narration: 'The Exception Center highlights long shifts, missing clock-outs, or unverified location punches.', caption: 'Resolve Payroll Exceptions' },
  { name: '36. Auditing Security Logs & User Activity', desc: 'Review system access logs, sensitive settings changes, and audit trails.', role: 'Owner', route: 'settings', target: 'card-settings-active', narration: 'Security audit logs record every sensitive setting change, login event, and permission modification.', caption: 'Audit System Security Log' },
  { name: '37. Configuring Custom User Permissions', desc: 'Grant or revoke section access for specific staff accounts.', role: 'Owner', route: 'staff', target: 'btn-add-staff', narration: 'Owners customize individual user access rights beyond default role baselines.', caption: 'Configure Custom Permissions' },
  { name: '38. Complete End-to-End Inventory Lifecycle Journey', desc: 'Track a gown from purchase order to stock receiving, sample fitting, and sale.', role: 'Inventory', route: 'inventory', target: 'btn-add-gown', narration: 'Follow a dress style from initial vendor purchase order to floor sample, bride selection, and final sale.', caption: 'Complete Inventory Journey' },
  { name: '39. Complete End-to-End Bridal Lifecycle Journey', desc: 'Experience a bride journey from web lead to consultation, gown purchase, alterations, and wedding day.', role: 'Bridal Consultant', route: 'dashboard', target: 'hero-banner', narration: 'Experience the complete bride lifecycle from initial website inquiry to wedding day gown delivery.', caption: 'Complete Bridal Journey' },
  { name: '40. Internal Business Communication & End-of-Day', desc: 'Ensure staff alignment with secure internal alerts, end-of-day digest settings, and notification hubs.', role: 'Manager', route: 'communications', target: 'label-daily-digest', narration: 'Beyond customer outreach, VowOS also manages your internal operational pulse via the Executive Digest and Notification Hub.', caption: 'Manage Internal Comm & End-of-Day' },
];

ADDITIONAL_SCENARIOS.forEach((item, idx) => {
  const scenarioNum = idx + 19;
  DEMO_SCENARIOS.push({
    id: `scenario-${scenarioNum}`,
    name: item.name,
    description: item.desc,
    targetRole: item.role,
    startRoute: item.route,
    estimatedMinutes: 3,
    difficulty: 'Intermediate',
    steps: [
      {
        id: `s${scenarioNum}-step1`,
        route: item.route,
        targetId: item.target,
        narrationText: item.narration,
        caption: item.caption,
        action: 'explain',
      },
      {
        id: `s${scenarioNum}-step2`,
        route: item.route,
        targetId: `nav-${item.route}`,
        narrationText: `Notice how VowOS keeps data perfectly synchronized across ${item.route} and all related store records.`,
        caption: `Verify ${item.name} Data Flow`,
        action: 'move',
      },
    ],
  });
});

export const MOBILE_DEMO_SCENARIOS: ScenarioDefinition[] = [
  {
    id: 'scenario-41-mobile-briefing',
    name: '41. Mobile Owner Morning Briefing',
    description: 'Review your boutique\'s daily KPI metrics and perform quick actions from your phone.',
    targetRole: 'Owner',
    startRoute: 'overview',
    estimatedMinutes: 2,
    difficulty: 'Beginner',
    steps: [
      {
        id: 'm41-step1',
        route: 'overview',
        mobileTargetId: 'mobile-kpi-revenue',
        narrationText: 'Start your morning by reviewing the Revenue card on your mobile dashboard.',
        caption: 'Review Revenue',
        action: 'explain'
      },
      {
        id: 'm41-step2',
        route: 'overview',
        mobileTargetId: 'mobile-quick-actions',
        narrationText: 'From here, you can launch quick actions like messaging staff or checking today\'s VIP appointments.',
        caption: 'Quick Actions',
        action: 'click'
      }
    ]
  },
  {
    id: 'scenario-42-mobile-schedule',
    name: '42. Mobile Schedule & Reassign',
    description: 'View today\'s suite schedule and quickly reassign an appointment to another stylist.',
    targetRole: 'Manager',
    startRoute: 'schedule',
    estimatedMinutes: 2,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 'm42-step1',
        route: 'schedule',
        mobileTargetId: 'mobile-schedule-card-0',
        narrationText: 'Tap on an upcoming appointment card to view the bride\'s details and assigned suite.',
        caption: 'Select Appointment',
        action: 'click'
      },
      {
        id: 'm42-step2',
        route: 'schedule',
        mobileTargetId: 'mobile-reassign-btn',
        narrationText: 'If a stylist calls in sick, you can easily reassign the suite to an available team member.',
        caption: 'Reassign Stylist',
        action: 'click'
      }
    ]
  },
  {
    id: 'scenario-43-mobile-customer',
    name: '43. Mobile Customer Lookup & Notes',
    description: 'Search for a bride, view her profile, and add a quick styling note directly from the floor.',
    targetRole: 'Stylist',
    startRoute: 'customers',
    estimatedMinutes: 2,
    difficulty: 'Beginner',
    steps: [
      {
        id: 'm43-step1',
        route: 'customers',
        mobileTargetId: 'mobile-customer-search',
        narrationText: 'Use the mobile search bar to quickly pull up a bride\'s profile when she walks in.',
        caption: 'Search Bride',
        action: 'explain'
      },
      {
        id: 'm43-step2',
        route: 'customers',
        mobileTargetId: 'mobile-customer-add-note',
        requiresMobileDrawer: true,
        narrationText: 'You can tap the actions drawer to add a quick note about her dress preferences while you are still in the suite.',
        caption: 'Add Note',
        action: 'click'
      }
    ]
  },
  {
    id: 'scenario-44-mobile-sale',
    name: '44. Mobile Quick Sale & Payment',
    description: 'Open the POS to process a deposit or accessory sale securely on your mobile device.',
    targetRole: 'Stylist',
    startRoute: 'sales',
    estimatedMinutes: 3,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 'm44-step1',
        route: 'sales',
        mobileTargetId: 'mobile-pos-new',
        narrationText: 'Start a new mobile checkout session to process veil or accessory purchases on the spot.',
        caption: 'New Mobile Sale',
        action: 'click'
      },
      {
        id: 'm44-step2',
        route: 'sales',
        mobileTargetId: 'mobile-pos-pay',
        narrationText: 'Collect payments securely through VowOS mobile without needing a physical terminal.',
        caption: 'Process Payment',
        action: 'explain'
      }
    ]
  },
  {
    id: 'scenario-45-mobile-payroll',
    name: '45. Mobile Payroll Approval',
    description: 'Review and approve staff timecards or corrections while away from the boutique.',
    targetRole: 'Owner',
    startRoute: 'payroll',
    estimatedMinutes: 2,
    difficulty: 'Intermediate',
    steps: [
      {
        id: 'm45-step1',
        route: 'payroll',
        requiresMobileDrawer: true,
        mobileTargetId: 'mobile-nav-payroll',
        narrationText: 'Open the More menu to access Payroll while on the go.',
        caption: 'Navigate to Payroll',
        action: 'click'
      },
      {
        id: 'm45-step2',
        route: 'payroll',
        mobileTargetId: 'mobile-payroll-approve',
        narrationText: 'Review pending timecard corrections and approve them with one tap before the pay period closes.',
        caption: 'Approve Corrections',
        action: 'click'
      }
    ]
  }
];

DEMO_SCENARIOS.push(...MOBILE_DEMO_SCENARIOS);
